import "server-only";

/**
 * The rule behind each question, for a student who just got one wrong.
 *
 * Keyed by topic rather than by generator, and that is the whole reason this
 * is affordable. A generator's topic already names the one idea it drills, and
 * the same idea recurs across courses — "Completing the square" is the same
 * method in Algebra 1 as in Algebra 2 — so 564 generators need 447 lines
 * between them, written once and shared.
 *
 * On memory, which is the constraint this whole feature was built under:
 *
 *   · Nothing is stored. A method is a constant, not session state, so there
 *     is no per-student, per-question or per-session record of any of it.
 *   · Nothing is shipped. This file is `server-only`, so the table never
 *     reaches a browser; a student receives the one line their own missed
 *     question earned, and only after it has been graded wrong.
 *   · Nothing is sent on a right answer. The verdict payload for a correct
 *     answer is unchanged, byte for byte.
 *
 * A method line is not the answer, and could be printed on the wall of the
 * room. It says which rule applies, not what it yields here — the numbers that
 * would turn it into a worked solution belong to the seed, and a generator
 * that wants to show them supplies `steps` instead (see `kit.ts`), which takes
 * precedence over anything here.
 */
const METHODS: Record<string, string> = {
  // ─── Algebra 1 ─────────────────────────────────────────
  "Classifying real numbers": "Naturals sit inside integers, integers inside rationals. A root that does not come out whole is irrational.",
  "Product rule": "Same base, multiplied: add the exponents.",
  "Quotient rule": "Same base, divided: subtract the bottom exponent from the top.",
  "Power of a power": "A power raised to a power: multiply the exponents.",
  "Negative exponents": "A negative exponent is a reciprocal: a^-n = 1/a^n.",
  "Scientific notation": "One non-zero digit before the point. Each place you move it changes the exponent by one.",
  "One-step equations": "Undo the one operation with its opposite, on both sides.",
  "Two-step equations": "Undo the addition first, then the multiplication — the order of operations run backwards.",
  "Negative coefficients": "Dividing by a negative flips the sign of everything on the other side.",
  "Rearranging for a value": "Treat every other letter as a number and isolate the one you want.",
  "Variables on both sides": "Collect the variable on one side first, then solve as usual.",
  "Distributing before solving": "Multiply through the bracket before you collect anything.",
  "Absolute value equations": "|x| = k splits into two equations: x = k and x = -k.",
  "Plotting a point": "(x, y): across first, then up. Signs decide the quadrant.",
  "Reflecting a point": "Across the x-axis negates y; across the y-axis negates x.",
  "Evaluating a function": "Substitute the input everywhere the variable appears, then simplify.",
  "Slope from two points": "Slope is rise over run: (y₂ - y₁)/(x₂ - x₁), in that order on both.",
  "Reading the sign of a slope": "Up to the right is positive, down to the right is negative, flat is zero, vertical is undefined.",
  "Slope and intercept from an equation": "In y = mx + b, m is the slope and b is where it crosses the y-axis.",
  "Evaluating a linear function": "Substitute the x-value into mx + b and simplify.",
  "Graphing from an equation": "Start at the y-intercept, then step by the slope: run across, rise up.",
  "Graphing from two points": "Two points fix a line. Find the slope between them, then the intercept.",
  "Parallel and perpendicular slopes": "Parallel lines share a slope. Perpendicular slopes are negative reciprocals — they multiply to -1.",
  "Systems by elimination": "Scale one equation so a variable cancels when you add, then back-substitute.",
  "Multiplying binomials": "Every term in the first bracket times every term in the second, then collect.",
  "Difference of squares": "a² - b² = (a + b)(a - b). No middle term.",
  "Perfect square trinomials": "a² ± 2ab + b² = (a ± b)². Check the middle term is twice the product.",
  "Factoring trinomials": "Find two numbers that multiply to the constant and add to the middle coefficient.",
  "Solving with the quadratic formula": "x = (-b ± √(b² - 4ac)) / 2a. The whole of -b is over the 2a.",
  "Computing the discriminant": "The discriminant is b² - 4ac.",
  "The nature of the roots": "Positive discriminant: two real roots. Zero: one repeated. Negative: two complex.",
  "Finding the nth term": "A geometric sequence is aₙ = a₁ · rⁿ⁻¹ — the exponent is one less than the position.",
  "Simplifying radicals": "Pull out the largest perfect square factor, then take its root outside.",
  "Mean and median": "Mean is the total over the count. Median is the middle value once sorted.",
  "Naming the property": "Commutative reorders, associative regroups, distributive multiplies through a bracket.",
  "Order of operations": "Brackets, exponents, then multiply and divide left to right, then add and subtract.",
  "Brackets and powers": "The exponent binds tighter than the minus sign unless a bracket says otherwise.",
  "Combining like terms": "Only terms with the identical variable part combine. Coefficients add; exponents do not.",
  "Translating a phrase": "'Less than' and 'subtracted from' reverse the order you read them in.",
  "Simplifying a square root": "Split the number into a perfect square times the rest, then take the root of the square.",
  "Clearing a fraction": "Multiply every term by the lowest common denominator — every term, including the whole numbers.",
  "How many solutions": "Ends in a true statement with no variable: infinitely many. Ends in a false one: none.",
  "Inequalities and the sign flip": "Multiplying or dividing by a negative reverses the inequality sign.",
  "Compound inequalities": "'And' is the overlap of the two regions; 'or' is everything either one covers.",
  "Absolute value inequalities": "|x| < k is a band between -k and k. |x| > k is the two pieces outside it.",
  "Recognising a function": "One input, one output. A repeated x with two different y-values is not a function.",
  "Discrete and continuous domains": "Countable things — people, tickets — are discrete. Measured things are continuous.",
  "Finding an intercept": "Set y = 0 for the x-intercept, x = 0 for the y-intercept.",
  "Evaluating a piecewise function": "Pick the piece whose condition the input satisfies, then substitute into that one only.",
  "Evaluating an absolute value function": "Work out the inside first, then take the absolute value, then apply what is outside.",
  "Describing a transformation": "Changes inside the function move it horizontally and the opposite way; changes outside move it vertically.",
  "Intercepts from standard form": "In Ax + By = C, the intercepts are C/A and C/B.",
  "Converting to standard form": "Clear fractions, move the variables left, and leave A positive.",
  "A line through two points": "Slope first, then substitute either point into y - y₁ = m(x - x₁).",
  "Inequalities in two variables": "Graph the boundary, dashed for strict, then shade the side a test point satisfies.",
  "An arithmetic sequence as a rule": "aₙ = a₁ + (n - 1)d. The common difference is the slope.",
  "Solving a system by graphing": "The solution is where the lines cross — the one point both equations accept.",
  "Systems by substitution": "Isolate one variable in one equation, then put that expression into the other.",
  "Choosing a method": "A variable already isolated favours substitution; matched coefficients favour elimination.",
  "Systems with no solution": "Same slope, different intercept: parallel, no solution. Same both: the same line, infinitely many.",
  "Break-even": "Break-even is where cost equals revenue. Set the two expressions equal.",
  "Maximising over a region": "The maximum of a linear objective sits at a corner of the feasible region. Test the corners.",
  "Systems of inequalities": "Shade each inequality; the solution is the region every shading covers.",
  "Classifying a polynomial": "Degree is the highest exponent; the name comes from the number of terms.",
  "Adding and subtracting polynomials": "Subtracting distributes the minus across every term in the second polynomial.",
  "The greatest common factor": "Take the largest number that divides every coefficient and the lowest power of each shared variable.",
  "Trinomials with a leading coefficient": "Split the middle term using two numbers multiplying to a·c and adding to b, then group.",
  "Factoring by grouping": "Pair the terms, factor each pair, and the shared bracket comes out.",
  "Sums and differences of cubes": "a³ ± b³ = (a ± b)(a² ∓ ab + b²). The middle sign of the trinomial is the opposite.",
  "Factoring completely": "Greatest common factor first, always. Then factor what is left, and check each piece again.",
  "The axis of symmetry": "x = -b/2a. The vertex sits on it.",
  "Placing a vertex": "In y = a(x - h)² + k the vertex is (h, k) — note the sign of h flips.",
  "Roots from factored form": "Each factor set to zero gives a root. (x - r) gives x = r.",
  "Reading a root off a graph": "The roots are where the curve meets the x-axis.",
  "The Zero Product Property": "If a product is zero, at least one factor is zero. Factor first, then set each to zero.",
  "Solving by square roots": "Isolate the square, then take both roots — the ± is not optional.",
  "Completing the square": "Halve the x-coefficient, square it, and add it to both sides.",
  "Complex solutions": "A negative under the root gives ±i√(that size). The roots come as a conjugate pair.",
  "Projectile motion": "The peak is at the vertex, t = -b/2a; the landing is the positive root.",
  "Exponential growth": "y = a(1 + r)ᵗ. The base is 1 plus the rate, not the rate.",
  "Exponential decay": "y = a(1 - r)ᵗ. A base below 1 is decay.",
  "The horizontal asymptote": "An exponential flattens towards its vertical shift, not towards zero, once shifted.",
  "Comparing rates of growth": "Exponential growth eventually overtakes any polynomial, however slow it starts.",
  "Recursive and explicit rules": "Recursive says how to get the next term; explicit jumps straight to the nth.",
  "Compound interest": "A = P(1 + r/n)^(nt). n is compoundings per year, and it appears twice.",
  "Adding radicals": "Only like radicals add. Simplify each first — they may become like.",
  "Radical equations": "Isolate the radical, square both sides, then check for extraneous roots.",
  "Simplifying a rational expression": "Factor top and bottom, then cancel whole factors — never individual terms.",
  "Multiplying rational expressions": "Factor everything, cancel across the multiplication, then write what is left.",
  "Adding rational expressions": "Find the lowest common denominator, rewrite both, then add the numerators only.",
  "Rational equations": "Multiply through by the common denominator, then discard any root that made it zero.",
  "Direct and inverse variation": "Direct is y = kx; inverse is y = k/x. Find k from the given pair first.",
  "The interquartile range": "IQR = Q3 - Q1, the spread of the middle half.",
  "The shape of a distribution": "The skew is named for the tail. A long right tail pulls the mean above the median.",
  "Reading a correlation coefficient": "r runs from -1 to 1: the sign is the direction, the size is the tightness.",
  "Residuals": "Residual = actual - predicted. Positive means the point sits above the line, and a pattern left in the residuals means the wrong model.",
  "Two-way tables": "Row and column totals are the margins; a conditional proportion divides by one margin, not the grand total.",
  "Correlation and causation": "A correlation may be explained by a lurking variable. Only an experiment establishes cause.",

  // ─── Geometry ──────────────────────────────────────────
  "Setting an angle": "Acute is under 90°, right is 90°, obtuse is between 90° and 180°.",
  "Segment addition": "If B is between A and C, then AB + BC = AC.",
  "Complements and supplements": "Complements sum to 90°, supplements to 180°.",
  "Midpoint": "The midpoint averages the coordinates: ((x₁ + x₂)/2, (y₁ + y₂)/2).",
  "Distance": "Distance is √((x₂ - x₁)² + (y₂ - y₁)²) — the Pythagorean theorem on the grid.",
  "The triangle angle sum": "The three angles of a triangle sum to 180°.",
  "The exterior angle theorem": "An exterior angle equals the sum of the two remote interior angles.",
  "The midsegment theorem": "A midsegment is parallel to the third side and half its length.",
  "The triangle inequality": "Any two sides must sum to more than the third. The third side lies strictly between their difference and their sum.",
  "Scale factor": "The scale factor is a ratio of corresponding lengths, image over original.",
  "Area ratios of similar figures": "Areas scale by the square of the scale factor.",
  "The Pythagorean theorem": "a² + b² = c², with c the side opposite the right angle.",
  "Finding the hypotenuse": "The hypotenuse is the root of the sum of the squares of the two legs.",
  "Special right triangles": "45-45-90 goes 1 : 1 : √2. 30-60-90 goes 1 : √3 : 2, the short leg opposite the 30°.",
  "Trigonometric ratios": "SOH-CAH-TOA: sine is opposite over hypotenuse, cosine adjacent over hypotenuse, tangent opposite over adjacent.",
  "Polygon angle sums": "Interior angles sum to (n - 2) × 180°. Exterior angles always sum to 360°.",
  "Central and inscribed angles": "A central angle equals its arc; an inscribed angle is half of it.",
  "The equation of a circle": "(x - h)² + (y - k)² = r². The centre signs flip, and the right side is r squared.",
  "Area of a sector": "A sector is its fraction of the circle: (θ/360) × πr².",
  "Volume of prisms and cylinders": "Volume is the base area times the height, for any prism or cylinder.",
  "Volume of cones": "A cone is a third of the cylinder around it: (1/3)πr²h.",
  "Spheres": "Volume is (4/3)πr³; surface area is 4πr².",
  "Scaling solids": "Scale a solid by k and area scales by k², volume by k³.",
  "Permutations and combinations": "Order matters in a permutation, not in a combination. C(n, r) = P(n, r)/r!.",
  "Independent and dependent events": "Independent events multiply directly. Dependent ones use the reduced pool for the second draw.",
  "Counting lines through points": "Each pair of points determines a line: C(n, 2) = n(n - 1)/2.",
  "Area and perimeter": "Perimeter is the distance around, area the space inside. Their units differ.",
  "Circumference": "Circumference is 2πr, or πd. Area is πr² — the one with the square.",
  "Continuing a pattern": "Find what changes from term to term, then check the rule against every term you were given.",
  "Converse, inverse, contrapositive": "Converse swaps, inverse negates, contrapositive does both. Only the contrapositive is always equivalent.",
  "Biconditionals": "A biconditional holds only when the statement and its converse are both true.",
  "The laws of logic": "Detachment: given p → q and p, conclude q. Syllogism: p → q and q → r give p → r.",
  "Properties of equality": "Name the operation that got you from one line to the next — added, subtracted, substituted, or transitive.",
  "Angle pairs on a transversal": "Corresponding and alternate pairs are equal; same-side interior angles are supplementary.",
  "Angles from parallel lines": "With parallel lines every angle is either the one given or its supplement.",
  "Proving lines parallel": "Lines are parallel when a pair of corresponding, alternate, or co-interior angles behaves as it should.",
  "Distance to a line": "The distance from a point to a line is measured along the perpendicular.",
  "Equations of parallel lines": "Keep the slope, change the intercept, then fit it through the given point.",
  "Translating a point": "A translation adds to each coordinate: (x + a, y + b).",
  "Rotating a point": "About the origin: 90° counterclockwise sends (x, y) to (-y, x); 180° to (-x, -y).",
  "A composition of two transformations": "Apply them in the order written, and take the output of the first as the input of the second.",
  "Lines of symmetry": "A regular n-gon has n lines of symmetry. Fold it and see which folds match.",
  "Dilating a point": "A dilation about the origin multiplies both coordinates by the scale factor.",
  "Rigid motions": "Translations, reflections and rotations preserve length and angle. Dilations do not.",
  "Similarity transformations": "A similarity is a rigid motion followed by a dilation — same shape, scaled size.",
  "Corresponding parts": "Once two triangles are congruent, every matching pair of parts is congruent. Read the letters in order.",
  "SSS and SAS": "SAS needs the angle *between* the two sides. An angle anywhere else does not prove congruence.",
  "ASA and AAS": "ASA has the side between the angles; AAS has it outside. Both prove congruence; SSA does not.",
  "Right triangle congruence": "HL works only for right triangles: hypotenuse and one leg.",
  "Isosceles triangles": "Equal sides face equal angles, and the theorem runs both ways.",
  "Bisectors": "A point on a perpendicular bisector is equidistant from the endpoints; on an angle bisector, from the sides.",
  "Centres of a triangle": "Perpendicular bisectors meet at the circumcentre, angle bisectors at the incentre.",
  "The centroid": "The medians meet at the centroid, two-thirds of the way from each vertex.",
  "Altitudes": "An altitude is perpendicular to the opposite side, and the three meet at the orthocentre.",
  "Sides and angles in order": "The largest angle faces the longest side. Order one and you have ordered the other.",
  "Solving a proportion": "Cross-multiply, then solve — but only once each side is a single fraction.",
  "Similarity criteria": "AA is enough for similarity. SSS needs all three ratios equal; SAS needs the included angle.",
  "Triangle proportionality": "A line parallel to one side cuts the other two proportionally.",
  "Proportional segments": "Set up the ratio with corresponding pieces in the same position on both sides.",
  "The geometric mean": "The altitude to the hypotenuse is the geometric mean of the two pieces it makes: h = √(pq).",
  "Solving a right triangle": "Pick the ratio that uses the two sides you have and the angle you want.",
  "Inverse trigonometric ratios": "Given two sides, the inverse ratio returns the angle: θ = tan⁻¹(opposite/adjacent).",
  "Angles of elevation": "Elevation is measured up from the horizontal, depression down from it, and the two are equal across a horizontal line.",
  "The Law of Sines": "a/sin A = b/sin B. Use it when a side and its opposite angle are paired.",
  "The Law of Cosines": "c² = a² + b² - 2ab·cos C. Use it for SSS or SAS, where the Law of Sines has no pair.",
  "Area from two sides and an angle": "Area = (1/2)ab·sin C, with C the angle between the two sides.",
  "Angles in a parallelogram": "Opposite angles are equal; consecutive angles are supplementary.",
  "Naming a special parallelogram": "Equal diagonals make a rectangle, perpendicular ones a rhombus, both a square.",
  "The midsegment of a trapezoid": "The midsegment is the average of the two parallel sides.",
  "The quadrilateral hierarchy": "Every square is a rectangle and a rhombus; the reverse does not follow.",
  "Radius and diameter": "The diameter is twice the radius. Formulas mostly want the radius.",
  "Tangents and radii": "A tangent meets the radius at the point of contact at 90°, which makes a right triangle.",
  "Arc length": "Arc length is (θ/360) × 2πr — the same fraction as the sector, applied to the circumference.",
  "Intersecting chords": "Two chords crossing inside a circle make equal products of their pieces.",
  "Inscribed angles": "An inscribed angle is half its arc. An angle in a semicircle is a right angle.",
  "Angles from two secants": "An angle outside the circle is half the *difference* of the two arcs; inside, half the sum.",
  "Secant segments": "From an outside point, whole times outside is equal for both secants.",
  "Area of a triangle": "Area = (1/2) × base × height, with the height perpendicular to the base you chose.",
  "Area of a regular polygon": "Area = (1/2) × apothem × perimeter.",
  "Composite areas": "Cut the figure into shapes you know, then add — or subtract the hole.",
  "Cross sections": "Imagine the slice as the plane passes through. A plane parallel to the base repeats the base.",
  "Surface area of a box": "Add the six faces: 2(lw + lh + wh).",
  "Surface area of a cone": "Base plus lateral: πr² + πrl, with l the slant height, not the vertical height.",
  "Cavalieri's principle": "Two solids with equal heights and equal cross-sectional areas have equal volume, however they lean.",
  "Density": "Density is mass over volume. Work out the volume first, in matching units.",
  "The counting principle": "Independent choices multiply: m ways then n ways is m × n.",
  "Experimental probability": "Experimental probability is successes over trials, and drifts towards the theoretical value with more trials.",
  "Geometric probability": "Geometric probability is the favourable area (or length) over the total.",
  "Conditional probability": "P(A|B) = P(A and B)/P(B). The condition shrinks the pool you divide by.",
  "Two-way tables and Venn diagrams": "The overlap is counted in both totals, so subtract it once: P(A or B) = P(A) + P(B) - P(A and B).",
  "Naming a construction": "Read what the arcs are equidistant from — that is what the construction has pinned down.",
  "Why a construction works": "Every arc is a set of points at one fixed distance, and equal radii make congruent triangles.",
  "The reason for a step": "Name the postulate, theorem or definition that entitles you to the line — never the line itself.",
  "The shape of a two-column proof": "It starts at the given and ends at the statement being proved, with a reason beside every line.",
  "Paragraph proofs": "Same logic as a two-column proof, written as prose. Every claim still needs its reason.",
  "Flowchart proofs": "Each box holds a statement with its reason underneath, and an arrow means the next box follows from it.",
  "Choosing the theorem": "Match the wording of the given to the wording of a theorem: supplementary, complementary, vertical, right, linear pair.",
  "Congruent supplements and complements": "Two angles supplementary to the same angle are congruent, and the same holds for complements.",
  "Constructing a perpendicular": "From a point off the line, cut the line twice first. From a point on it, mark two equidistant points first.",
  "Constructing a parallel": "Copying an angle across a transversal makes corresponding angles congruent, which forces the lines parallel.",
  "CPCTC": "Once the triangles are congruent, matching parts are equal — set the two expressions equal and solve.",
  "What CPCTC allows": "CPCTC applies only after congruence is established, and only to matching parts.",
  "Proving with the distance formula": "Compute the lengths with √((x₂ - x₁)² + (y₂ - y₁)²) and compare them.",
  "Placing a figure on the axes": "Put a vertex at the origin and a side on an axis, so the coordinates carry as many zeros as possible.",
  "The assumption in an indirect proof": "Assume the exact negation of the claim — including the boundary case, which is where these go wrong.",
  "Reaching a contradiction": "The assumption must collide with the given or with a theorem. That collision is what proves the claim.",
  "Tests for a parallelogram": "Both pairs of opposite sides, both pairs of opposite angles, bisecting diagonals, or one pair both parallel and congruent.",
  "Diagonals that bisect each other": "Bisected means the two halves are equal — set the expressions equal and solve.",
  "Where the diagonals cross": "Diagonals that bisect each other share a midpoint, so the crossing is the midpoint of either one.",
  "Perpendicular diagonals": "A rhombus has perpendicular diagonals, so the slopes are negative reciprocals.",

  // ─── Algebra 2 ─────────────────────────────────────────
  "Matrix multiplication": "Row times column: multiply pairs across and sum. Order matters.",
  "Determinants": "For a 2×2, the determinant is ad - bc.",
  "Powers of i": "Powers of i cycle every four: i, -1, -i, 1. Take the exponent mod 4.",
  "Multiplying complex numbers": "Expand as binomials, then replace i² with -1.",
  "Complex conjugates": "The conjugate flips the sign of the imaginary part; the product is a² + b², always real.",
  "The Remainder Theorem": "Dividing by (x - c) leaves the remainder f(c). Just evaluate.",
  "The Rational Root Theorem": "Possible rational roots are ± (a factor of the constant) over (a factor of the leading coefficient).",
  "Horizontal asymptotes": "Compare degrees: bottom bigger gives y = 0, equal gives the ratio of leading coefficients, top bigger gives none.",
  "Rational exponents": "a^(m/n) is the nth root of a to the m. The denominator is the root.",
  "Function composition": "f(g(x)) means substitute all of g into f. The inner one runs first.",
  "Inverse functions": "Swap x and y, then solve for y. The inverse undoes the original.",
  "Evaluating a logarithm": "log_b(x) asks what exponent turns b into x.",
  "Properties of logarithms": "A product becomes a sum, a quotient a difference, and an exponent comes out front.",
  "Solving exponential equations": "Match the bases if you can; otherwise take a logarithm of both sides.",
  "Degrees to radians": "Multiply by π/180 to get radians, by 180/π to go back.",
  "The unit circle": "On the unit circle the coordinates are (cos θ, sin θ). Learn the quadrant signs.",
  "Amplitude and period": "For a·sin(bx), amplitude is |a| and period is 2π/b.",
  "Arithmetic sequences": "aₙ = a₁ + (n - 1)d — one fewer step than the position number.",
  "Arithmetic series": "Sₙ = (n/2)(a₁ + aₙ): the number of terms times the average of the ends.",
  "Infinite geometric series": "It sums to a₁/(1 - r), and only when |r| < 1.",
  "Ellipses": "x²/a² + y²/b² = 1. The larger denominator sits under the major axis.",
  "Probability as a percentage": "Favourable over total, then multiply by 100. It cannot exceed 100%.",
  "z-scores": "z = (x - μ)/σ: how many standard deviations from the mean, signed.",
  "Systems in two variables": "The solution is the point both equations accept — where the two graphs cross.",
  "Systems in three variables": "Eliminate one variable from two different pairs, then solve the 2×2 that is left.",
  "Adding matrices": "Add entry by entry. Only same-sized matrices add.",
  "Entries of an inverse matrix": "For a 2×2, swap a and d, negate b and c, and divide by the determinant.",
  "When a system can be solved by matrices": "A system has a unique matrix solution exactly when the determinant is non-zero.",
  "The vertex from vertex form": "y = a(x - h)² + k has vertex (h, k). The h sign flips.",
  "Solving by factoring": "Set the equation to zero first, then factor, then set each factor to zero.",
  "The discriminant": "b² - 4ac. Its sign, not its value, tells you the kind of roots.",
  "Quadratic inequalities": "Find the roots, then test a point in each interval they cut the line into.",
  "A line meeting a parabola": "Set the two equal and solve. The discriminant counts the intersections.",
  "End behaviour": "The leading term decides. Even degree sends both ends the same way; odd degree opposite ways.",
  "Intercepts of a factored polynomial": "Each factor gives an x-intercept; the y-intercept is the product of the constants.",
  "Multiplying polynomials": "Every term against every term, then collect like powers.",
  "Polynomial division": "Long or synthetic division. Leave a zero placeholder for every missing power.",
  "The Factor Theorem": "(x - c) is a factor exactly when f(c) = 0.",
  "Counting roots": "A degree-n polynomial has exactly n roots counted with multiplicity, real or complex.",
  "Conjugate pairs": "Complex roots of a real polynomial come in conjugate pairs, so they arrive two at a time.",
  "Building a polynomial from zeros": "Each zero r gives a factor (x - r). Multiply them out.",
  "Turning points": "A degree-n polynomial has at most n - 1 turning points.",
  "Polynomial inequalities": "Factor, mark the roots on a line, and test the sign in each interval.",
  "Binomial coefficients": "The coefficient of the term is C(n, k) — row n of Pascal's triangle.",
  "Dividing rational expressions": "Multiply by the reciprocal of the second, then cancel factors.",
  "Complex fractions": "Multiply top and bottom by the common denominator of the little fractions.",
  "Holes": "A factor that cancels from top and bottom leaves a hole, not an asymptote.",
  "Slant asymptotes": "When the numerator is exactly one degree higher, divide — the quotient is the slant asymptote.",
  "Zeros of a rational function": "The zeros come from the numerator, once anything shared with the denominator has cancelled.",
  "Excluded values": "Exclude every value that makes an original denominator zero, even one that cancels.",
  "Rational inequalities": "Test the intervals cut by both the zeros and the undefined points.",
  "The constant of variation": "Substitute the given pair to find k first, then use it.",
  "nth roots": "An even root of a negative is not real; an odd root is.",
  "Rationalising a denominator": "Multiply top and bottom by the radical, or by the conjugate when there are two terms.",
  "The domain of a square root": "The inside must be at least zero. Solve that inequality.",
  "Combining two functions": "Add, subtract or multiply the outputs at the same input; division also excludes the zeros of the divisor.",
  "Recognising an inverse": "Two functions are inverse when both compositions return x.",
  "Growth and decay factors": "The factor is 1 + r for growth and 1 - r for decay. A factor above 1 grows.",
  "The natural base": "e ≈ 2.718. Continuous growth is A = Pe^(rt).",
  "Graphing an exponential": "It passes through (0, a), never crosses its asymptote, and the base decides which way it bends.",
  "Logarithmic notation": "log_b(x) = y and b^y = x say the same thing.",
  "Change of base": "log_b(x) = ln x / ln b, or with any base you like on top and bottom.",
  "Logarithmic equations": "Condense to one log, rewrite as an exponential, then check the argument is positive.",
  "Doubling": "Doubling time solves 2 = (1 + r)ᵗ, which means a logarithm.",
  "Logistic growth": "Logistic growth accelerates, then flattens at the carrying capacity in the denominator.",
  "Right triangle ratios": "SOH-CAH-TOA, and label opposite and adjacent relative to the angle you are using.",
  "Signs by quadrant": "All, Sine, Tangent, Cosine — positive in quadrants I, II, III, IV respectively.",
  "Reference angles": "The reference angle is the acute angle to the x-axis. Take the value from it and the sign from the quadrant.",
  "Amplitude and midline": "Midline is the average of the maximum and minimum; amplitude is half their difference.",
  "Asymptotes of the tangent graph": "Tangent is undefined where cosine is zero: at π/2 plus multiples of π.",
  "Inverse trigonometric functions": "Each inverse has a restricted range, so it returns one angle rather than infinitely many.",
  "Solving a trigonometric equation": "Find the reference angle, then every angle in the interval that shares that value.",
  "The Pythagorean identity": "sin²θ + cos²θ = 1. The quadrant decides the sign of the one you solve for.",
  "Simplifying with identities": "Convert everything to sines and cosines, then look for a Pythagorean identity.",
  "Sum and difference formulas": "cos(A ± B) = cos A cos B ∓ sin A sin B — the sign on the right is the opposite one.",
  "Double-angle formulas": "sin 2θ = 2 sin θ cos θ; cos 2θ has three equivalent forms.",
  "Period of a sinusoid": "Period is 2π/b for sine and cosine, π/b for tangent.",
  "Recursive sequences": "Start at the given term and apply the rule one step at a time.",
  "Geometric sequences": "aₙ = a₁ · rⁿ⁻¹, where r is the ratio between consecutive terms.",
  "Geometric series": "Sₙ = a₁(1 - rⁿ)/(1 - r).",
  "Sigma notation": "The index runs from the bottom value to the top inclusive. Count the terms before summing.",
  "The inductive step": "Assume the statement for n = k, then prove it for k + 1 using that assumption.",
  "Distance between points": "√((x₂ - x₁)² + (y₂ - y₁)²).",
  "The focus of a parabola": "For (x - h)² = 4p(y - k), the focus is p from the vertex and the directrix is p the other way.",
  "The centre of a circle": "Complete the square in x and in y to get (x - h)² + (y - k)² = r².",
  "Asymptotes of a hyperbola": "For x²/a² - y²/b² = 1 the asymptotes are y = ±(b/a)x.",
  "Classifying a conic": "Compare the squared terms: none is a line, one is a parabola, equal is a circle, unequal same-sign is an ellipse, opposite-sign is a hyperbola.",
  "A line meeting a circle": "Substitute the line into the circle and read the discriminant: two, one, or no intersections.",
  "Drawing without replacement": "The second draw has one fewer in the pool, and one fewer of whatever came out.",
  "Binomial probability": "C(n, k)·pᵏ·(1 - p)ⁿ⁻ᵏ — the combination counts the orders.",
  "Sampling": "A sample is only unbiased when every member of the population had an equal chance.",
  "Margin of error": "Margin of error shrinks with the square root of the sample size, so four times the sample halves it.",
  "Choosing a model": "Constant differences mean linear, constant second differences quadratic, constant ratios exponential.",

  // ─── Precalculus ───────────────────────────────────────
  "Average rate of change": "(f(b) - f(a))/(b - a) — the slope of the secant between the two points.",
  "Vertical asymptotes": "Where the denominator is zero and the numerator is not.",
  "Sinusoidal transformations": "In a·sin(b(x - c)) + d: a is amplitude, 2π/b the period, c the phase shift, d the midline.",
  "Pythagorean identities": "sin² + cos² = 1, and dividing through by cos² or sin² gives the other two.",
  "Vector magnitude": "|v| = √(x² + y²).",
  "The dot product": "a·b = x₁x₂ + y₁y₂, a number rather than a vector. Zero means perpendicular.",
  "Eliminating the parameter": "Solve one equation for t and substitute into the other.",
  "Eccentricity": "e = c/a. Zero is a circle, under 1 an ellipse, 1 a parabola, above 1 a hyperbola.",
  "The Binomial Theorem": "The term in aⁿ⁻ᵏbᵏ has coefficient C(n, k). Count k from zero.",
  "Evaluating limits algebraically": "Substitute; if that gives 0/0, factor or rationalise and cancel, then substitute again.",
  "One-sided limits": "Approach from one side only. The two-sided limit exists only when both agree.",
  "The difference quotient": "(f(x + h) - f(x))/h, expanded and simplified until the h cancels.",
  "Domain of a rational function": "Everything except where the denominator is zero.",
  "Extrema": "A maximum or minimum is where the graph turns. Local is within a neighbourhood, absolute across the whole domain.",
  "Even and odd functions": "Even: f(-x) = f(x), symmetric about the y-axis. Odd: f(-x) = -f(x), symmetric about the origin.",
  "Concavity": "Concave up holds water and has an increasing slope; concave down is the reverse.",
  "Piecewise functions": "Choose the branch whose condition the input meets, then use only that expression.",
  "Transformations": "Inside the function is horizontal and inverted; outside is vertical and as written.",
  "Restricting a domain": "Restrict until the function passes the horizontal line test, so an inverse exists.",
  "Building a linear model": "Slope is the rate, intercept the starting value. Write it in context.",
  "Zeros and degree": "A polynomial of degree n has n zeros with multiplicity, and at most n x-intercepts.",
  "Multiplicity": "Odd multiplicity crosses the axis; even multiplicity touches and turns back.",
  "Complex zeros": "Non-real zeros of a real polynomial come in conjugate pairs.",
  "Odd and even degree": "Odd degree must cross the x-axis at least once; even degree need not.",
  "Modelling with a polynomial": "Match the number of turning points to the degree, then fit the coefficients.",
  "Arithmetic and geometric sequences": "Constant difference is arithmetic; constant ratio is geometric.",
  "Growth factors": "The growth factor is the ratio between consecutive terms, not the difference.",
  "Continuous rates": "Continuous growth is Pe^(rt); the equivalent annual factor is e^r.",
  "Asymptotes of an exponential": "An exponential approaches its vertical shift, which is the horizontal asymptote.",
  "Logarithms as inverses": "log_b and b^x undo one another, so log_b(bˣ) = x.",
  "Exponential inequalities": "Take logs of both sides; if the base is below 1, the inequality flips.",
  "Semi-log plots": "Exponential data plots as a straight line on a semi-log scale; its slope is the growth rate.",
  "Doubling models": "The doubling time is where the factor reaches 2. Solve with a logarithm.",
  "Cycles and periods": "The period is the horizontal length of one full cycle; frequency is its reciprocal.",
  "Sinusoidal models": "Midline is the average, amplitude half the range, period the time for one cycle.",
  "The tangent function": "Tangent is sin/cos: period π, zeros where sine is zero, asymptotes where cosine is.",
  "Reciprocal functions": "Secant is 1/cos, cosecant 1/sin, cotangent 1/tan. Each blows up where its partner is zero.",
  "Ranges of inverse functions": "arcsin returns [-π/2, π/2], arccos returns [0, π], arctan returns (-π/2, π/2).",
  "Solving trigonometric equations": "Solve for the reference angle, then add every full period inside the interval.",
  "Double-angle identities": "sin 2θ = 2 sin θ cos θ; cos 2θ = cos²θ - sin²θ.",
  "Polar to rectangular": "x = r cos θ, y = r sin θ.",
  "Polar graphs": "r = a + b cos θ makes a limaçon or cardioid; r = a cos(nθ) makes a rose, with n or 2n petals.",
  "Rates in polar form": "Look at how r changes as θ turns — the distance from the pole, not the height.",
  "Adding vectors": "Add components separately: (x₁ + x₂, y₁ + y₂).",
  "Unit vectors": "Divide the vector by its own magnitude; the result has length 1.",
  "Resultants": "Break each vector into components, add them, then rebuild magnitude and direction.",
  "A point on a parametric curve": "Substitute the parameter into both equations to get x and y at that instant.",
  "Parametric motion": "x(t) and y(t) give position; the path is the trace, and t is the timing along it.",
  "Matrices as transformations": "The columns of the matrix say where (1, 0) and (0, 1) land.",
  "Systems as matrices": "Write it as AX = B and solve with the inverse, or with the determinant.",
  "Determinants and area": "The absolute value of the determinant is the area of the image of the unit square.",
  "The directrix": "Every point of a parabola is equidistant from the focus and the directrix.",
  "Axes of an ellipse": "The major axis is 2a, the minor 2b, and a² = b² + c² locates the foci.",
  "Vertices of a hyperbola": "The vertices sit a from the centre along the axis of the positive squared term.",
  "Rotating the axes": "A cross term xy means the conic is rotated. The angle satisfies cot 2θ = (A - C)/B.",
  "Conics in polar form": "r = ed/(1 ± e cos θ). The eccentricity e names the conic.",
  "Conics in parametric form": "An ellipse traces as x = a cos t, y = b sin t.",
  "Explicit sequences": "An explicit rule gives aₙ from n directly, without the previous term.",
  "Summation formulas": "Sum of the first n integers is n(n + 1)/2; of squares, n(n + 1)(2n + 1)/6.",
  "Limits by substitution": "If the function is continuous there, the limit is just the value.",
  "Limits from a table": "Read what the outputs approach from both sides. The value at the point does not decide it.",
  "Limits at infinity": "Compare the leading degrees, or divide every term by the highest power of x.",

  // ─── AP Calculus AB ────────────────────────────────────
  "Limits by algebraic manipulation": "0/0 is an invitation, not an answer. Factor, rationalise, or use a common denominator, then cancel.",
  "The Power Rule": "d/dx[xⁿ] = n·xⁿ⁻¹: bring the exponent down, then drop it by one.",
  "The Product Rule": "(fg)' = f'g + fg'. It is not the product of the derivatives.",
  "The Quotient Rule": "(f/g)' = (f'g - fg')/g². The order in the numerator matters.",
  "The Chain Rule": "Differentiate the outside, leave the inside alone, then multiply by the inside's derivative.",
  "Higher-order derivatives": "Differentiate again, and again. Each pass applies the same rules to the new function.",
  "Straight-line motion": "Position differentiates to velocity, velocity to acceleration. Speed is |velocity|.",
  "Related rates": "Differentiate the relationship with respect to t, then substitute the numbers — not before.",
  "L'Hospital's Rule": "Only for 0/0 or ∞/∞: differentiate top and bottom separately, then re-evaluate.",
  "Finding a critical point": "Where f' is zero or undefined, and inside the domain.",
  "Increasing and decreasing intervals": "f increases where f' > 0 and decreases where f' < 0.",
  "The Second Derivative Test": "At a critical point, f'' > 0 is a minimum and f'' < 0 is a maximum. Zero tells you nothing.",
  "Definite integrals": "Antidifferentiate, then evaluate at the top limit minus the bottom.",
  "Antiderivatives": "Reverse the Power Rule: raise the exponent by one and divide by the new exponent. Add C.",
  "Integration by substitution": "Let u be the inside function, replace dx with du/u', and change the limits too.",
  "Average value": "The average value of f on [a, b] is (1/(b - a))∫f dx.",
  "Area between curves": "∫(top - bottom) across the interval, splitting wherever they swap.",
  "Average and instantaneous rates": "Average rate is the secant slope; instantaneous is the tangent slope, the limit of the secant.",
  "Reading limit notation": "The limit describes what the outputs approach, not what the function does at the point.",
  "Limits from a graph": "Follow the curve in from both sides. An open circle does not change the limit.",
  "Properties of limits": "Limits distribute across sums, products and quotients — as long as each one exists.",
  "Choosing a procedure": "Try substitution first. Only when it gives 0/0 do you factor, rationalise or use conjugates.",
  "The Squeeze Theorem": "If g ≤ f ≤ h and the two outer limits agree, f is trapped at the same value.",
  "One-sided limits that disagree": "When the left and right limits differ, the two-sided limit does not exist.",
  "Types of discontinuity": "Removable is a hole, jump is a step, infinite is an asymptote.",
  "Continuity at a point": "The limit must exist, the value must exist, and the two must be equal.",
  "Continuity on an interval": "Continuous on an interval means continuous at every point in it, one-sided at the ends.",
  "Removing a discontinuity": "Set the value equal to the limit — that is the only choice that patches the hole.",
  "The Intermediate Value Theorem": "A continuous function on [a, b] takes every value between f(a) and f(b) at least once.",
  "The definition of the derivative": "f'(x) = lim(h→0) (f(x + h) - f(x))/h.",
  "Estimating a derivative": "Use the slope between the nearest points, ideally straddling the one you want.",
  "Differentiability": "Differentiable implies continuous, not the other way. Corners and cusps are continuous but not differentiable.",
  "Sum and constant multiple rules": "Derivatives pass through sums, and constants come along for the ride.",
  "Standard derivatives": "sin → cos, cos → -sin, eˣ → eˣ, ln x → 1/x.",
  "Derivatives of the other ratios": "tan → sec², sec → sec·tan, cot → -csc², csc → -csc·cot.",
  "Implicit differentiation": "Differentiate both sides in x, attaching dy/dx to every y term, then solve for dy/dx.",
  "Derivatives of inverses": "(f⁻¹)'(a) = 1/f'(f⁻¹(a)) — the reciprocal of the slope at the matching point.",
  "Inverse trigonometric derivatives": "arcsin' = 1/√(1 - x²), arctan' = 1/(1 + x²).",
  "Choosing a rule": "Look at the outermost operation: a product, a quotient, or a composition decides the rule.",
  "The derivative in context": "The derivative carries the units of the output over the units of the input.",
  "Rates in context": "State what is changing, how fast, in what units, and at what moment.",
  "Setting up a related rate": "Write the geometric relationship first, differentiate in t, and only then substitute.",
  "Linearisation": "L(x) = f(a) + f'(a)(x - a) — the tangent line, used as the function nearby.",
  "The Mean Value Theorem": "Somewhere inside the interval the tangent slope equals the average slope across it.",
  "The First Derivative Test": "A sign change in f' from + to - is a maximum; - to + is a minimum.",
  "The Candidates Test": "For an absolute extremum, evaluate f at every critical point and at both endpoints.",
  "Points of inflection": "Where f'' changes sign. f'' = 0 alone is not enough.",
  "A function and its derivative": "Where f' is positive f rises; where f' turns, f has an inflection point.",
  "Setting up an optimisation": "Write the quantity to optimise, use the constraint to reduce it to one variable, then differentiate.",
  "Solving an optimisation": "Find the critical points, test them, and check the endpoints of the feasible range.",
  "Tangents to an implicit curve": "Differentiate implicitly for dy/dx, then substitute the point to get the slope.",
  "Accumulating change": "The integral of a rate over an interval is the total change across it.",
  "Riemann sums": "Left sums lag and right sums lead on an increasing function. The midpoint is usually closest.",
  "What an integral means": "A definite integral is signed area: what is below the axis subtracts.",
  "Accumulation functions": "F(x) = ∫ₐˣ f(t) dt accumulates as x moves, and F' = f.",
  "Reading an accumulation function": "Add the signed areas as x advances. Below the axis subtracts.",
  "Properties of definite integrals": "Flipping the limits negates; adjacent intervals add; constants come out front.",
  "Rewriting before integrating": "Expand, split the fraction, or use an identity until every term is a power you can integrate.",
  "Choosing a technique": "Substitution when an inside function's derivative is present; otherwise rewrite until it is a standard form.",
  "Writing a differential equation": "'Proportional to' becomes dy/dt = ky. Translate each phrase into a term.",
  "Verifying a solution": "Differentiate the candidate and substitute it back in. Both sides must match.",
  "Slope fields": "Each dash has slope dy/dx at that point. A solution curve follows the dashes.",
  "Reading a slope field": "Trace a curve that stays tangent to every dash it passes.",
  "Separation of variables": "Get all the y with dy and all the x with dx, integrate both sides, and add one constant.",
  "Particular solutions": "Find the general solution first, then use the initial condition to pin down C.",
  "Exponential models": "dy/dt = ky solves to y = y₀e^(kt).",
  "Motion from velocity": "Displacement is ∫v dt; total distance is ∫|v| dt, split where v changes sign.",
  "Accumulation in context": "Starting amount plus the integral of the rate gives the amount at the end.",
  "Area integrated in y": "When the curves are easier as x = g(y), integrate right minus left, in dy.",
  "Curves that cross three times": "Find every intersection, then integrate each strip with the correct curve on top.",
  "Square cross sections": "Volume is ∫(side)² dx, with the side taken from the distance between the curves.",
  "Other cross sections": "Volume is ∫A(x) dx. Write the area of one slice in terms of the distance between the curves.",
  "The disc method": "V = π∫r² dx, with r the distance from the axis to the curve.",
  "Discs about another axis": "The radius is measured from the axis of rotation, so subtract before you square.",
  "The washer method": "V = π∫(R² - r²) dx. Square each radius separately — never subtract first.",
  "Washers about another axis": "Shift both radii to the new axis, then take the difference of the squares.",

  // ─── AP Calculus BC ────────────────────────────────────
  "Integration by parts": "∫u dv = uv - ∫v du. Choose u by LIATE — the part that simplifies when differentiated.",
  "Improper integrals": "Replace the infinite limit with b, integrate, then take the limit as b goes to infinity.",
  "Euler's method": "Step along the tangent: yₙ₊₁ = yₙ + h·f(xₙ, yₙ), recomputing the slope each step.",
  "Parametric derivatives": "dy/dx = (dy/dt)/(dx/dt).",
  "Area of a polar region": "A = (1/2)∫r² dθ. The half and the square are both easy to lose.",
  "p-series": "Σ1/nᵖ converges exactly when p > 1.",
  "The Ratio Test": "Take the limit of |aₙ₊₁/aₙ|: under 1 converges, over 1 diverges, exactly 1 is inconclusive.",
  "Taylor coefficients": "The coefficient of (x - a)ⁿ is f⁽ⁿ⁾(a)/n!. The factorial is not optional.",
  "Radius of convergence": "Apply the Ratio Test to the series and solve the resulting inequality for x.",
  "Partial fractions": "Factor the denominator, split into one fraction per factor, and solve for the numerators.",
  "Logistic models": "dP/dt = kP(1 - P/L). Growth is fastest at half the carrying capacity.",
  "Second derivatives in parametric form": "d²y/dx² = (d/dt of dy/dx) ÷ (dx/dt) — divide by dx/dt again at the end.",
  "Parametric arc length": "L = ∫√((dx/dt)² + (dy/dt)²) dt.",
  "Differentiating a vector function": "Differentiate each component separately.",
  "Integrating a vector function": "Integrate each component separately, with a constant vector.",
  "Speed from a velocity vector": "Speed is the magnitude: √(x'(t)² + y'(t)²).",
  "Differentiating in polar form": "Convert with x = r cos θ and y = r sin θ, then use the parametric rule in θ.",
  "Area between polar curves": "(1/2)∫(outer² - inner²) dθ, over the θ range where that ordering holds.",
  "Convergence and divergence": "A series converges when its partial sums approach a limit.",
  "The nth Term Test": "If the terms do not go to zero, the series diverges. Terms going to zero prove nothing.",
  "The Integral Test": "For positive decreasing terms, the series and the matching improper integral share a fate.",
  "Comparison tests": "Compare with a p-series or geometric series, directly or by taking the limit of the ratio.",
  "The Alternating Series Test": "Alternating, decreasing in size, and tending to zero: it converges.",
  "Absolute and conditional convergence": "Test the absolute values. Convergent there is absolute; divergent there but convergent alternating is conditional.",
  "The alternating series error bound": "The error is smaller than the first term you left out.",
  "The Lagrange error bound": "|error| ≤ max|f⁽ⁿ⁺¹⁾| · |x - a|ⁿ⁺¹/(n + 1)!.",
  "Maclaurin series": "eˣ = Σxⁿ/n!, sin x has odd powers alternating, cos x even powers alternating.",
  "Functions as power series": "Start from 1/(1 - x) = Σxⁿ for |x| < 1, then substitute, differentiate or integrate.",
};

/**
 * The few topic names that mean different things in different courses.
 *
 * Sharing a method across courses is the point of keying by topic, and it is
 * right almost everywhere: completing the square is completing the square. But
 * "Arc length" is a fraction of a circle in Geometry, s = rθ in Precalculus and
 * an integral in Calculus BC, and one line cannot be all three. Keyed by course
 * and topic, checked first, and deliberately tiny — a long list here would mean
 * the topic names themselves had stopped being specific enough.
 */
const BY_COURSE: Record<string, string> = {
  "math/precalculus|Arc length": "s = rθ, with θ in radians.",
  "math/ap-calculus-bc|Arc length": "L = ∫√(1 + (dy/dx)²) dx.",
};

/**
 * The rule behind a topic, or undefined for one with nothing written yet.
 *
 * Undefined is a normal result rather than a failure: the diagnosis on the
 * client stands on its own, and a missing method line simply means the student
 * gets the shorter of the two explanations.
 */
export function methodFor(topic: string, subunitId?: string): string | undefined {
  const course = subunitId?.split("/").slice(0, 2).join("/");
  const special = course ? BY_COURSE[`${course}|${topic}`] : undefined;
  return special ?? METHODS[topic];
}

/** How many topics have a method on file. Used by `npm run check:coaching`. */
export function methodCount(): number {
  return Object.keys(METHODS).length;
}

/**
 * The explanation that rides back with a wrong verdict, or undefined when
 * there is nothing on file for the topic.
 *
 * Steps the generator worked out for this exact roll win, because they carry
 * the student's own numbers rather than the general shape of the rule. The
 * topic method is the fallback, and is why the whole feature costs one table
 * of 447 strings rather than one worked solution per generator.
 *
 * Called only on a miss. A correct answer never reaches here, so a right
 * verdict is the same payload it has always been.
 */
export function coachingFor(
  steps: string[] | undefined,
  topic: string,
  subunitId: string,
): string[] | undefined {
  if (steps?.length) return steps;
  const method = methodFor(topic, subunitId);
  return method ? [method] : undefined;
}
