/**
 * Math course outlines: the Grade 5 → AP Calculus BC sequence, unit by unit
 * and subunit by subunit.
 *
 * This file is the skeleton only — no questions. It lives apart from
 * `curriculum.ts` so ten courses' worth of outline does not bury the stocked
 * question banks there. `curriculum.ts` turns these specs into Units, and a
 * course stays unplayable in the UI until its subunits actually hold questions.
 *
 * Difficulty is set per subunit because it drives the clock and the XP, not
 * what a student is allowed to pick. It rises with the course and again for
 * proof-heavy, multi-step, and modelling topics.
 *
 * AP unit titles and topic numbering follow the College Board Course and Exam
 * Description for AP Calculus AB/BC.
 */

import type { Difficulty } from "./curriculum";

/** One subunit: CED-style code, name, and how long it takes to answer. */
export type SubunitSpec = [code: string, name: string, difficulty: Difficulty];

/** One unit: code, name, and its subunits in order. */
export type UnitSpec = [code: string, name: string, subunits: SubunitSpec[]];

/**
 * Grade 5. The first course in the sequence, and the first written to the
 * depth rule from the start: every subunit gets three generators that differ
 * in the shape of the task, not three sets of digits.
 */
export const GRADE_5: UnitSpec[] = [
  [
    "unit-1",
    "Place Value and Decimals",
    [
      ["1.1", "Place value through millions and thousandths", "easy"],
      ["1.2", "Reading, writing, and comparing decimals", "easy"],
      ["1.3", "Rounding decimals", "easy"],
      ["1.4", "Powers of 10 and exponent notation", "easy"],
      ["1.5", "Multiplying and dividing by powers of 10", "medium"],
      ["1.6", "Adding and subtracting decimals", "easy"],
      ["1.7", "Multiplying decimals", "medium"],
      ["1.8", "Dividing decimals", "medium"],
    ],
  ],
  [
    "unit-2",
    "Whole Number Operations and Number Theory",
    [
      ["2.1", "Multi-digit multiplication", "easy"],
      ["2.2", "Multi-digit division with remainders", "medium"],
      ["2.3", "Interpreting remainders in context", "medium"],
      ["2.4", "Factors, multiples, and divisibility rules", "easy"],
      ["2.5", "Prime and composite numbers", "easy"],
      ["2.6", "Prime factorization", "medium"],
      ["2.7", "Greatest common factor", "medium"],
      ["2.8", "Least common multiple", "medium"],
    ],
  ],
  [
    "unit-3",
    "Fractions — Addition and Subtraction",
    [
      ["3.1", "Equivalent fractions", "easy"],
      ["3.2", "Comparing and ordering fractions", "medium"],
      ["3.3", "Adding fractions with unlike denominators", "medium"],
      ["3.4", "Subtracting fractions with unlike denominators", "medium"],
      ["3.5", "Adding and subtracting mixed numbers", "medium"],
      ["3.6", "Regrouping with mixed numbers", "hard"],
      ["3.7", "Estimating fraction sums and differences", "medium"],
      ["3.8", "Fraction word problems", "hard"],
    ],
  ],
  [
    "unit-4",
    "Fractions — Multiplication and Division",
    [
      ["4.1", "Fraction as division", "medium"],
      ["4.2", "Multiplying a fraction by a whole number", "easy"],
      ["4.3", "Multiplying two fractions", "medium"],
      ["4.4", "Area models for fraction multiplication", "medium"],
      ["4.5", "Scaling: comparing a product to its factors", "hard"],
      ["4.6", "Multiplying mixed numbers", "medium"],
      ["4.7", "Dividing a whole number by a unit fraction", "medium"],
      ["4.8", "Dividing a unit fraction by a whole number", "medium"],
      ["4.9", "Converting between fractions and decimals", "easy"],
    ],
  ],
  [
    "unit-5",
    "Expressions and Patterns",
    [
      ["5.1", "Order of operations with grouping symbols", "medium"],
      ["5.2", "Writing numerical expressions from words", "medium"],
      ["5.3", "Interpreting expressions without evaluating", "hard"],
      ["5.4", "Numerical patterns and rules", "easy"],
      ["5.5", "Generating two related patterns", "medium"],
      ["5.6", "Graphing pattern pairs as ordered pairs", "medium"],
      ["5.7", "Introduction to variables", "easy"],
    ],
  ],
  [
    "unit-6",
    "The Coordinate Plane",
    [
      ["6.1", "Points, axes, and the origin", "easy"],
      ["6.2", "Plotting ordered pairs in the first quadrant", "easy"],
      ["6.3", "Reading coordinates from a graph", "easy"],
      ["6.4", "Distance between points on an axis", "medium"],
      ["6.5", "Representing real-world problems on a grid", "medium"],
      ["6.6", "Extending to all four quadrants", "medium"],
    ],
  ],
  [
    "unit-7",
    "Measurement and Volume",
    [
      ["7.1", "Converting within the metric system", "easy"],
      ["7.2", "Converting within the customary system", "medium"],
      ["7.3", "Multi-step conversion problems", "hard"],
      ["7.4", "Volume as unit cubes", "easy"],
      ["7.5", "Volume of a rectangular prism", "medium"],
      ["7.6", "Volume formulas: V = lwh and V = Bh", "medium"],
      ["7.7", "Volume of composite solids", "hard"],
      ["7.8", "Line plots with fractional measurements", "medium"],
    ],
  ],
  [
    "unit-8",
    "Two-Dimensional Geometry",
    [
      ["8.1", "Classifying triangles by sides and angles", "easy"],
      ["8.2", "Classifying quadrilaterals", "easy"],
      ["8.3", "The quadrilateral hierarchy", "medium"],
      ["8.4", "Parallel and perpendicular sides", "easy"],
      ["8.5", "Area of rectangles with fractional side lengths", "medium"],
      ["8.6", "Perimeter and area problems", "medium"],
    ],
  ],
];

/**
 * Grade 6. Ratio and rate reasoning, negative numbers, and the first algebra:
 * expressions with letters in them, and equations to solve rather than
 * arithmetic to carry out.
 */
export const GRADE_6: UnitSpec[] = [
  [
    "unit-1",
    "Ratios and Rates",
    [
      ["1.1", "Ratio language and notation", "easy"],
      ["1.2", "Equivalent ratios and ratio tables", "easy"],
      ["1.3", "Unit rates", "medium"],
      ["1.4", "Comparing unit rates", "medium"],
      ["1.5", "Graphing ratio relationships", "medium"],
      ["1.6", "Converting measurement units with ratios", "medium"],
      ["1.7", "Percent as a rate per hundred", "easy"],
      ["1.8", "Finding a percent of a number", "medium"],
      ["1.9", "Finding the whole given a part and a percent", "hard"],
    ],
  ],
  [
    "unit-2",
    "Operations with Fractions and Decimals",
    [
      ["2.1", "Dividing a fraction by a fraction", "medium"],
      ["2.2", "Interpreting fraction division in context", "hard"],
      ["2.3", "Multi-digit decimal operations", "medium"],
      ["2.4", "The standard division algorithm", "medium"],
      ["2.5", "GCF and LCM in context", "medium"],
      ["2.6", "The distributive property with the GCF", "hard"],
      ["2.7", "Fluency across fractions, decimals, and percents", "medium"],
    ],
  ],
  [
    "unit-3",
    "Rational Numbers",
    [
      ["3.1", "Negative numbers and their meaning", "easy"],
      ["3.2", "The number line extended", "easy"],
      ["3.3", "Opposites and the additive inverse", "easy"],
      ["3.4", "Absolute value", "easy"],
      ["3.5", "Comparing and ordering rational numbers", "medium"],
      ["3.6", "Absolute value in context", "medium"],
      ["3.7", "The four-quadrant coordinate plane", "easy"],
      ["3.8", "Reflections across the axes", "medium"],
      ["3.9", "Distance between points sharing a coordinate", "medium"],
    ],
  ],
  [
    "unit-4",
    "Expressions",
    [
      ["4.1", "Exponents and repeated multiplication", "easy"],
      ["4.2", "Order of operations with exponents", "medium"],
      ["4.3", "Writing algebraic expressions", "medium"],
      ["4.4", "Identifying parts of an expression", "easy"],
      ["4.5", "Evaluating expressions by substitution", "medium"],
      ["4.6", "The distributive property", "medium"],
      ["4.7", "Combining like terms", "medium"],
      ["4.8", "Equivalent expressions", "medium"],
      ["4.9", "Formulas and evaluation", "medium"],
    ],
  ],
  [
    "unit-5",
    "Equations and Inequalities",
    [
      ["5.1", "What it means to solve an equation", "easy"],
      ["5.2", "One-step addition and subtraction equations", "easy"],
      ["5.3", "One-step multiplication and division equations", "easy"],
      ["5.4", "Writing equations from word problems", "hard"],
      ["5.5", "Inequalities and their meaning", "easy"],
      ["5.6", "Graphing inequalities on a number line", "medium"],
      ["5.7", "Dependent and independent variables", "medium"],
      ["5.8", "Tables, graphs, and equations of relationships", "hard"],
    ],
  ],
  [
    "unit-6",
    "Geometry",
    [
      ["6.1", "Area of parallelograms", "easy"],
      ["6.2", "Area of triangles", "medium"],
      ["6.3", "Area of trapezoids", "medium"],
      ["6.4", "Area of composite figures", "hard"],
      ["6.5", "Polygons on the coordinate plane", "medium"],
      ["6.6", "Nets of three-dimensional figures", "medium"],
      ["6.7", "Surface area from nets", "hard"],
      ["6.8", "Volume with fractional edge lengths", "hard"],
    ],
  ],
  [
    "unit-7",
    "Statistics",
    [
      ["7.1", "Statistical versus non-statistical questions", "easy"],
      ["7.2", "Dot plots and histograms", "easy"],
      ["7.3", "Measures of center: mean, median, mode", "medium"],
      ["7.4", "The mean as a balance point", "hard"],
      ["7.5", "Measures of variability: range and IQR", "medium"],
      ["7.6", "Mean absolute deviation", "hard"],
      ["7.7", "Box plots", "medium"],
      ["7.8", "Choosing an appropriate measure", "hard"],
      ["7.9", "Describing a distribution in context", "medium"],
    ],
  ],
];

/**
 * Grade 7. Proportional reasoning carried through percent, geometry and
 * probability, and the first equations worth calling algebra: two steps,
 * rational coefficients, and a variable on both sides.
 */
export const GRADE_7: UnitSpec[] = [
  [
    "unit-1",
    "Proportional Relationships",
    [
      ["1.1", "Unit rates with fractions", "medium"],
      ["1.2", "Recognizing proportional relationships in tables", "medium"],
      ["1.3", "Recognizing proportional relationships in graphs", "medium"],
      ["1.4", "The constant of proportionality", "medium"],
      ["1.5", "Equations of proportional relationships", "medium"],
      ["1.6", "Interpreting points on a proportional graph", "hard"],
      ["1.7", "Solving proportions", "medium"],
      ["1.8", "Scale drawings and scale factor", "hard"],
      ["1.9", "Multi-step ratio problems", "hard"],
    ],
  ],
  [
    "unit-2",
    "Operations with Rational Numbers",
    [
      ["2.1", "Adding integers on a number line", "easy"],
      ["2.2", "Adding rational numbers", "medium"],
      ["2.3", "Subtraction as adding the opposite", "medium"],
      ["2.4", "Distance as the absolute value of a difference", "medium"],
      ["2.5", "Multiplying rational numbers and sign rules", "medium"],
      ["2.6", "Dividing rational numbers", "medium"],
      ["2.7", "Terminating and repeating decimals", "medium"],
      ["2.8", "Order of operations with rational numbers", "hard"],
      ["2.9", "Applying rational number operations", "hard"],
    ],
  ],
  [
    "unit-3",
    "Percent Applications",
    [
      ["3.1", "Percent increase and decrease", "medium"],
      ["3.2", "Tax, tip, and commission", "medium"],
      ["3.3", "Discount and markup", "medium"],
      ["3.4", "Simple interest", "medium"],
      ["3.5", "Percent error", "hard"],
      ["3.6", "Successive percent changes", "hard"],
      ["3.7", "Working backward from a final amount", "hard"],
    ],
  ],
  [
    "unit-4",
    "Expressions and Equations",
    [
      ["4.1", "Adding and subtracting linear expressions", "medium"],
      ["4.2", "Factoring linear expressions", "medium"],
      ["4.3", "Expanding with the distributive property", "medium"],
      ["4.4", "Rewriting expressions to reveal meaning", "hard"],
      ["4.5", "Two-step equations", "medium"],
      ["4.6", "Equations with rational coefficients", "hard"],
      ["4.7", "Equations with the variable on both sides", "hard"],
      ["4.8", "Two-step inequalities", "medium"],
      ["4.9", "Reversing the inequality sign", "medium"],
      ["4.10", "Modeling with equations and inequalities", "hard"],
    ],
  ],
  [
    "unit-5",
    "Geometry — Angles and Figures",
    [
      ["5.1", "Complementary and supplementary angles", "easy"],
      ["5.2", "Vertical and adjacent angles", "easy"],
      ["5.3", "Solving for unknown angles", "medium"],
      ["5.4", "Triangle inequality and constructing triangles", "medium"],
      ["5.5", "Conditions determining a unique triangle", "hard"],
      ["5.6", "Cross sections of three-dimensional figures", "medium"],
      ["5.7", "Circumference of a circle", "easy"],
      ["5.8", "Area of a circle", "medium"],
      ["5.9", "Composite figures involving circles", "hard"],
      ["5.10", "Area, volume, and surface area problems", "hard"],
    ],
  ],
  [
    "unit-6",
    "Probability",
    [
      ["6.1", "Likelihood and the probability scale", "easy"],
      ["6.2", "Theoretical probability", "medium"],
      ["6.3", "Experimental probability", "medium"],
      ["6.4", "Comparing theoretical and experimental results", "hard"],
      ["6.5", "Simulation", "hard"],
      ["6.6", "Sample space of compound events", "medium"],
      ["6.7", "Tree diagrams and organized lists", "medium"],
      ["6.8", "Probability of compound events", "hard"],
      ["6.9", "Independent and dependent events", "hard"],
    ],
  ],
  [
    "unit-7",
    "Statistics and Sampling",
    [
      ["7.1", "Populations and samples", "easy"],
      ["7.2", "Random sampling and bias", "medium"],
      ["7.3", "Estimating a population from a sample", "hard"],
      ["7.4", "Variability across samples", "hard"],
      ["7.5", "Comparing two populations", "hard"],
      ["7.6", "Visual overlap of distributions", "medium"],
      ["7.7", "Drawing inferences from data", "hard"],
    ],
  ],
];

/**
 * Grade 8. Linear relationships worked concretely — tables, graphs, rate of
 * change, slope-intercept, solving by graphing — plus transformations,
 * Pythagoras and the first bivariate data.
 *
 * Deliberately pitched below Algebra 1 rather than duplicating it: the same
 * content arrives there formally, in point-slope and standard form, with
 * literal equations and elimination. A student who finishes this course should
 * find Algebra 1's early units familiar but more abstract.
 */
export const GRADE_8: UnitSpec[] = [
  [
    "unit-1",
    "The Number System",
    [
      ["1.1", "Rational and irrational numbers", "easy"],
      ["1.2", "Converting repeating decimals to fractions", "hard"],
      ["1.3", "Approximating irrational numbers", "medium"],
      ["1.4", "Comparing and ordering irrational numbers", "medium"],
      ["1.5", "Square roots and cube roots", "medium"],
      ["1.6", "Solving x² = p and x³ = p", "medium"],
    ],
  ],
  [
    "unit-2",
    "Exponents and Scientific Notation",
    [
      ["2.1", "Properties of integer exponents", "medium"],
      ["2.2", "Zero and negative exponents", "medium"],
      ["2.3", "Simplifying exponential expressions", "hard"],
      ["2.4", "Scientific notation", "easy"],
      ["2.5", "Operations in scientific notation", "hard"],
      ["2.6", "Comparing magnitudes", "medium"],
      ["2.7", "Choosing units for very large or small quantities", "medium"],
    ],
  ],
  [
    "unit-3",
    "Linear Equations in One Variable",
    [
      ["3.1", "Solving multi-step equations", "medium"],
      ["3.2", "Equations with variables on both sides", "medium"],
      ["3.3", "Equations with rational coefficients", "hard"],
      ["3.4", "One solution, no solution, infinitely many", "hard"],
      ["3.5", "Justifying each step", "medium"],
      ["3.6", "Modeling with linear equations", "hard"],
    ],
  ],
  [
    "unit-4",
    "Linear Relationships and Slope",
    [
      ["4.1", "Proportional relationships as lines through the origin", "easy"],
      ["4.2", "Slope as a constant rate of change", "medium"],
      ["4.3", "Similar triangles and why slope is constant", "hard"],
      ["4.4", "Slope from two points", "medium"],
      ["4.5", "Slope-intercept form", "medium"],
      ["4.6", "Graphing from an equation", "medium"],
      ["4.7", "Writing an equation from a graph", "medium"],
      ["4.8", "Comparing relationships across representations", "hard"],
      ["4.9", "Interpreting slope and intercept in context", "hard"],
    ],
  ],
  [
    "unit-5",
    "Systems of Linear Equations",
    [
      ["5.1", "What a solution to a system means", "easy"],
      ["5.2", "Solving systems by graphing", "medium"],
      ["5.3", "Estimating solutions from a graph", "medium"],
      ["5.4", "Solving by substitution", "hard"],
      ["5.5", "Solving by elimination", "hard"],
      ["5.6", "Systems with no solution or infinitely many", "hard"],
      ["5.7", "Modeling with systems", "hard"],
    ],
  ],
  [
    "unit-6",
    "Functions",
    [
      ["6.1", "What makes a relation a function", "easy"],
      ["6.2", "Function notation and language", "medium"],
      ["6.3", "Functions from tables, graphs, and equations", "medium"],
      ["6.4", "Linear versus nonlinear functions", "medium"],
      ["6.5", "Rate of change and initial value", "medium"],
      ["6.6", "Comparing functions in different forms", "hard"],
      ["6.7", "Sketching a graph from a verbal description", "hard"],
      ["6.8", "Qualitative graph analysis", "hard"],
    ],
  ],
  [
    "unit-7",
    "Transformations, Congruence, and Similarity",
    [
      ["7.1", "Translations", "easy"],
      ["7.2", "Reflections", "easy"],
      ["7.3", "Rotations", "medium"],
      ["7.4", "Sequences of transformations", "hard"],
      ["7.5", "Congruence through rigid motions", "medium"],
      ["7.6", "Dilations and scale factor", "medium"],
      ["7.7", "Similarity through transformations", "hard"],
      ["7.8", "Angles from parallel lines and a transversal", "medium"],
      ["7.9", "Angle sum and exterior angle of a triangle", "medium"],
      ["7.10", "The angle–angle criterion for similarity", "hard"],
    ],
  ],
  [
    "unit-8",
    "The Pythagorean Theorem",
    [
      ["8.1", "Understanding the Pythagorean theorem", "easy"],
      ["8.2", "Proving the Pythagorean theorem", "hard"],
      ["8.3", "Finding a missing side", "medium"],
      ["8.4", "The converse of the Pythagorean theorem", "medium"],
      ["8.5", "Applications in two dimensions", "medium"],
      ["8.6", "Distance between points on the coordinate plane", "medium"],
      ["8.7", "Applications in three dimensions", "hard"],
    ],
  ],
  [
    "unit-9",
    "Volume and Bivariate Data",
    [
      ["9.1", "Volume of cylinders", "medium"],
      ["9.2", "Volume of cones", "medium"],
      ["9.3", "Volume of spheres", "medium"],
      ["9.4", "Composite solid volume problems", "hard"],
      ["9.5", "Scatter plots and association", "medium"],
      ["9.6", "Clustering, outliers, and linear association", "medium"],
      ["9.7", "Fitting a line informally", "hard"],
      ["9.8", "Interpreting the slope and intercept of a fitted line", "hard"],
      ["9.9", "Two-way tables and relative frequency", "hard"],
    ],
  ],
];

export const ALGEBRA_1: UnitSpec[] = [
  [
    "unit-1",
    "Foundations of Algebra",
    [
      ["1.1", "The real number system and classification", "easy"],
      ["1.2", "Properties of operations", "easy"],
      ["1.3", "Order of operations and evaluating expressions", "easy"],
      ["1.4", "Algebraic expressions: terms, coefficients, like terms", "easy"],
      ["1.5", "Translating verbal statements into algebraic form", "medium"],
      ["1.6", "Exponent rules: product, quotient, power, zero, negative", "medium"],
      ["1.7", "Scientific notation and operations", "easy"],
      ["1.8", "Introduction to radicals and simplifying square roots", "easy"],
    ],
  ],
  [
    "unit-2",
    "Linear Equations and Inequalities in One Variable",
    [
      ["2.1", "One- and two-step equations", "medium"],
      ["2.2", "Multi-step equations with variables on both sides", "medium"],
      ["2.3", "Equations involving fractions and decimals", "medium"],
      ["2.4", "Literal equations and rearranging formulas", "medium"],
      ["2.5", "Special cases: no solution and infinitely many solutions", "medium"],
      ["2.6", "Solving and graphing linear inequalities", "medium"],
      ["2.7", "Compound inequalities (and / or)", "medium"],
      ["2.8", "Absolute value equations", "medium"],
      ["2.9", "Absolute value inequalities", "medium"],
    ],
  ],
  [
    "unit-3",
    "Functions and Relations",
    [
      ["3.1", "Relations, domain, and range", "medium"],
      ["3.2", "Definition of a function and the vertical line test", "easy"],
      ["3.3", "Function notation and evaluation", "easy"],
      ["3.4", "Discrete versus continuous domains", "medium"],
      ["3.5", "Interpreting graphs: intercepts, intervals, extrema", "medium"],
      ["3.6", "Piecewise-defined functions", "medium"],
      ["3.7", "Step functions and absolute value functions", "medium"],
      ["3.8", "Transformations: shifts, reflections, stretches, compressions", "medium"],
    ],
  ],
  [
    "unit-4",
    "Linear Functions",
    [
      ["4.1", "Rate of change and slope", "medium"],
      ["4.2", "Slope-intercept form", "medium"],
      ["4.3", "Point-slope form", "medium"],
      ["4.4", "Standard form and intercepts", "medium"],
      ["4.5", "Converting between forms", "medium"],
      ["4.6", "Parallel and perpendicular lines", "medium"],
      ["4.7", "Writing equations from graphs, points, and contexts", "medium"],
      ["4.8", "Graphing linear inequalities in two variables", "medium"],
      ["4.9", "Arithmetic sequences as linear functions", "medium"],
    ],
  ],
  [
    "unit-5",
    "Systems of Equations and Inequalities",
    [
      ["5.1", "Solving systems by graphing", "medium"],
      ["5.2", "Solving by substitution", "medium"],
      ["5.3", "Solving by elimination", "medium"],
      ["5.4", "Selecting an efficient method", "medium"],
      ["5.5", "Systems with no solution or infinitely many solutions", "medium"],
      ["5.6", "Applications: mixture, rate, and break-even problems", "hard"],
      ["5.7", "Systems of linear inequalities", "medium"],
      ["5.8", "Introduction to linear programming", "hard"],
    ],
  ],
  [
    "unit-6",
    "Polynomials and Factoring",
    [
      ["6.1", "Classifying polynomials by degree and number of terms", "easy"],
      ["6.2", "Adding and subtracting polynomials", "medium"],
      ["6.3", "Multiplying monomials, binomials, and polynomials", "medium"],
      ["6.4", "Special products: difference of squares, perfect square trinomials", "medium"],
      ["6.5", "Factoring out the greatest common factor", "medium"],
      ["6.6", "Factoring trinomials with leading coefficient 1", "medium"],
      ["6.7", "Factoring trinomials with leading coefficient other than 1", "hard"],
      ["6.8", "Factoring by grouping", "medium"],
      ["6.9", "Factoring special forms, including sum and difference of cubes", "medium"],
      ["6.10", "Complete factoring strategy", "medium"],
    ],
  ],
  [
    "unit-7",
    "Quadratic Functions and Equations",
    [
      ["7.1", "Graphing quadratics in standard form: vertex, axis of symmetry, direction", "medium"],
      ["7.2", "Vertex form and transformations", "medium"],
      ["7.3", "Intercept (factored) form", "medium"],
      ["7.4", "Solving quadratics by graphing", "medium"],
      ["7.5", "Solving by factoring and the Zero Product Property", "medium"],
      ["7.6", "Solving by square roots", "medium"],
      ["7.7", "Completing the square", "hard"],
      ["7.8", "The quadratic formula", "medium"],
      ["7.9", "The discriminant and the nature of roots", "medium"],
      ["7.10", "Introduction to complex solutions", "easy"],
      ["7.11", "Modeling with quadratics: projectile motion and area optimization", "hard"],
    ],
  ],
  [
    "unit-8",
    "Exponential Functions and Sequences",
    [
      ["8.1", "Geometric sequences", "medium"],
      ["8.2", "Exponential growth models", "medium"],
      ["8.3", "Exponential decay models", "medium"],
      ["8.4", "Graphing exponential functions and horizontal asymptotes", "medium"],
      ["8.5", "Comparing linear, quadratic, and exponential growth", "medium"],
      ["8.6", "Recursive versus explicit formulas", "medium"],
      ["8.7", "Compound interest applications", "medium"],
    ],
  ],
  [
    "unit-9",
    "Radical and Rational Expressions",
    [
      ["9.1", "Simplifying radical expressions", "medium"],
      ["9.2", "Operations with radicals", "medium"],
      ["9.3", "Solving radical equations and extraneous solutions", "medium"],
      ["9.4", "Simplifying rational expressions", "medium"],
      ["9.5", "Multiplying and dividing rational expressions", "medium"],
      ["9.6", "Adding and subtracting rational expressions", "medium"],
      ["9.7", "Solving rational equations", "medium"],
      ["9.8", "Direct, inverse, and joint variation", "medium"],
    ],
  ],
  [
    "unit-10",
    "Data Analysis and Statistics",
    [
      ["10.1", "Measures of center and spread", "medium"],
      ["10.2", "Box plots and the five-number summary", "medium"],
      ["10.3", "Histograms and shapes of distributions", "medium"],
      ["10.4", "Scatter plots and correlation", "medium"],
      ["10.5", "Lines of best fit and residuals", "medium"],
      ["10.6", "Two-way frequency tables", "medium"],
      ["10.7", "Interpreting models: correlation versus causation", "medium"],
    ],
  ],
];

export const GEOMETRY: UnitSpec[] = [
  [
    "unit-1",
    "Foundations of Geometry",
    [
      ["1.1", "Points, lines, planes, and space", "medium"],
      ["1.2", "Segments, rays, and angle measure", "medium"],
      ["1.3", "Segment addition and midpoint", "medium"],
      ["1.4", "Angle addition and angle pair relationships", "medium"],
      ["1.5", "Distance and midpoint on the coordinate plane", "medium"],
      ["1.6", "Constructions with compass and straightedge", "medium"],
      ["1.7", "Perimeter, circumference, and area formulas", "medium"],
    ],
  ],
  [
    "unit-2",
    "Reasoning and Proof",
    [
      ["2.1", "Inductive reasoning and conjecture", "medium"],
      ["2.2", "Conditional statements: converse, inverse, contrapositive", "medium"],
      ["2.3", "Biconditionals and precise definitions", "easy"],
      ["2.4", "Deductive reasoning and the laws of logic", "medium"],
      ["2.5", "Algebraic proof and properties of equality", "hard"],
      ["2.6", "Two-column proofs", "hard"],
      ["2.7", "Paragraph and flowchart proofs", "hard"],
      ["2.8", "Proving segment and angle theorems", "hard"],
    ],
  ],
  [
    "unit-3",
    "Parallel and Perpendicular Lines",
    [
      ["3.1", "Lines, transversals, and angle pairs", "medium"],
      ["3.2", "Angles formed by parallel lines", "medium"],
      ["3.3", "Proving lines parallel", "hard"],
      ["3.4", "Perpendicular lines and distance from a point to a line", "medium"],
      ["3.5", "Slopes of parallel and perpendicular lines", "medium"],
      ["3.6", "Writing equations of parallel and perpendicular lines", "medium"],
      ["3.7", "Constructing parallel and perpendicular lines", "medium"],
    ],
  ],
  [
    "unit-4",
    "Transformations and Symmetry",
    [
      ["4.1", "Translations", "medium"],
      ["4.2", "Reflections", "medium"],
      ["4.3", "Rotations", "medium"],
      ["4.4", "Compositions of transformations", "medium"],
      ["4.5", "Line and rotational symmetry", "medium"],
      ["4.6", "Dilations and scale factor", "medium"],
      ["4.7", "Rigid motions and the definition of congruence", "easy"],
      ["4.8", "Similarity transformations", "medium"],
    ],
  ],
  [
    "unit-5",
    "Triangles and Congruence",
    [
      ["5.1", "Triangle classification and the angle sum theorem", "easy"],
      ["5.2", "The exterior angle theorem", "medium"],
      ["5.3", "Congruent figures and CPCTC", "medium"],
      ["5.4", "SSS and SAS congruence", "medium"],
      ["5.5", "ASA and AAS congruence", "medium"],
      ["5.6", "HL congruence for right triangles", "medium"],
      ["5.7", "Isosceles and equilateral triangle theorems", "medium"],
      ["5.8", "Proofs using congruent triangles", "hard"],
      ["5.9", "Coordinate proofs", "hard"],
    ],
  ],
  [
    "unit-6",
    "Relationships Within Triangles",
    [
      ["6.1", "Perpendicular bisectors and angle bisectors", "medium"],
      ["6.2", "Circumcenter and incenter", "medium"],
      ["6.3", "Medians and the centroid", "medium"],
      ["6.4", "Altitudes and the orthocenter", "medium"],
      ["6.5", "The midsegment theorem", "medium"],
      ["6.6", "The triangle inequality theorem", "medium"],
      ["6.7", "Inequalities in one triangle and in two triangles", "medium"],
      ["6.8", "Indirect proof", "hard"],
    ],
  ],
  [
    "unit-7",
    "Similarity",
    [
      ["7.1", "Ratios, proportions, and their properties", "medium"],
      ["7.2", "Similar polygons", "medium"],
      ["7.3", "AA, SSS, and SAS similarity criteria", "medium"],
      ["7.4", "The triangle proportionality theorem", "medium"],
      ["7.5", "Proportional segments and parallel lines", "medium"],
      ["7.6", "Geometric mean and right triangle similarity", "medium"],
      ["7.7", "Perimeter and area ratios of similar figures", "medium"],
    ],
  ],
  [
    "unit-8",
    "Right Triangles and Trigonometry",
    [
      ["8.1", "The Pythagorean theorem and its converse", "medium"],
      ["8.2", "Pythagorean triples", "easy"],
      ["8.3", "Special right triangles: 45–45–90 and 30–60–90", "medium"],
      ["8.4", "Sine, cosine, and tangent ratios", "medium"],
      ["8.5", "Solving right triangles", "medium"],
      ["8.6", "Inverse trigonometric ratios", "medium"],
      ["8.7", "Angles of elevation and depression", "medium"],
      ["8.8", "The Law of Sines", "medium"],
      ["8.9", "The Law of Cosines", "medium"],
      ["8.10", "Area of a triangle using trigonometry", "medium"],
    ],
  ],
  [
    "unit-9",
    "Quadrilaterals and Polygons",
    [
      ["9.1", "Polygon interior and exterior angle sums", "medium"],
      ["9.2", "Parallelograms and their properties", "medium"],
      ["9.3", "Proving a quadrilateral is a parallelogram", "hard"],
      ["9.4", "Rectangles, rhombuses, and squares", "medium"],
      ["9.5", "Trapezoids and kites", "medium"],
      ["9.6", "Coordinate proofs with quadrilaterals", "hard"],
      ["9.7", "The quadrilateral classification hierarchy", "easy"],
    ],
  ],
  [
    "unit-10",
    "Circles",
    [
      ["10.1", "Parts of a circle", "easy"],
      ["10.2", "Tangent lines and their properties", "medium"],
      ["10.3", "Arcs and central angles", "medium"],
      ["10.4", "Arc length and introduction to radian measure", "medium"],
      ["10.5", "Chords and chord theorems", "medium"],
      ["10.6", "Inscribed angles and inscribed polygons", "medium"],
      ["10.7", "Angle relationships from secants and tangents", "medium"],
      ["10.8", "Segment lengths in circles", "medium"],
      ["10.9", "The equation of a circle", "medium"],
      ["10.10", "Areas of sectors and segments", "medium"],
    ],
  ],
  [
    "unit-11",
    "Area and Volume",
    [
      ["11.1", "Areas of triangles and quadrilaterals", "medium"],
      ["11.2", "Areas of regular polygons and the apothem", "medium"],
      ["11.3", "Composite figures and shaded regions", "medium"],
      ["11.4", "Three-dimensional figures and cross sections", "medium"],
      ["11.5", "Surface area of prisms and cylinders", "medium"],
      ["11.6", "Surface area of pyramids and cones", "medium"],
      ["11.7", "Volume of prisms and cylinders", "medium"],
      ["11.8", "Volume of pyramids and cones", "medium"],
      ["11.9", "Spheres: surface area and volume", "medium"],
      ["11.10", "Cavalieri's principle", "hard"],
      ["11.11", "Similar solids and the effect of scaling", "medium"],
      ["11.12", "Density and geometric modeling", "medium"],
    ],
  ],
  [
    "unit-12",
    "Probability",
    [
      ["12.1", "Sample spaces and the counting principle", "medium"],
      ["12.2", "Permutations and combinations", "medium"],
      ["12.3", "Theoretical versus experimental probability", "medium"],
      ["12.4", "Geometric probability", "medium"],
      ["12.5", "Independent and dependent events", "medium"],
      ["12.6", "Conditional probability", "medium"],
      ["12.7", "Two-way tables and Venn diagrams", "medium"],
    ],
  ],
];

export const ALGEBRA_2: UnitSpec[] = [
  [
    "unit-1",
    "Linear Systems and Matrices",
    [
      ["1.1", "Linear functions and inequalities review", "easy"],
      ["1.2", "Systems in two variables", "medium"],
      ["1.3", "Systems in three variables", "medium"],
      ["1.4", "Matrix operations", "medium"],
      ["1.5", "Matrix multiplication", "medium"],
      ["1.6", "Determinants and Cramer's Rule", "medium"],
      ["1.7", "Inverse matrices", "medium"],
      ["1.8", "Solving systems using matrices", "medium"],
    ],
  ],
  [
    "unit-2",
    "Quadratic Functions and Complex Numbers",
    [
      ["2.1", "Quadratic forms and transformations", "medium"],
      ["2.2", "Solving by factoring and square roots", "medium"],
      ["2.3", "Completing the square and vertex form", "hard"],
      ["2.4", "The quadratic formula and the discriminant", "medium"],
      ["2.5", "Imaginary numbers and powers of i", "medium"],
      ["2.6", "Operations with complex numbers", "medium"],
      ["2.7", "Complex conjugates and division", "medium"],
      ["2.8", "Complex solutions of quadratic equations", "medium"],
      ["2.9", "Quadratic inequalities", "medium"],
      ["2.10", "Systems involving quadratic equations", "medium"],
    ],
  ],
  [
    "unit-3",
    "Polynomial Functions",
    [
      ["3.1", "Degree, leading coefficient, and end behavior", "medium"],
      ["3.2", "Graphing polynomial functions", "medium"],
      ["3.3", "Adding, subtracting, and multiplying polynomials", "medium"],
      ["3.4", "Polynomial long division", "medium"],
      ["3.5", "Synthetic division", "medium"],
      ["3.6", "The Remainder and Factor Theorems", "medium"],
      ["3.7", "The Rational Root Theorem", "medium"],
      ["3.8", "The Fundamental Theorem of Algebra", "medium"],
      ["3.9", "Finding all real and complex zeros", "medium"],
      ["3.10", "Writing polynomial functions from zeros", "medium"],
      ["3.11", "Multiplicity and turning points", "medium"],
      ["3.12", "Polynomial inequalities", "medium"],
      ["3.13", "The Binomial Theorem and Pascal's Triangle", "medium"],
    ],
  ],
  [
    "unit-4",
    "Rational Functions",
    [
      ["4.1", "Simplifying rational expressions", "medium"],
      ["4.2", "Multiplying and dividing rational expressions", "medium"],
      ["4.3", "Adding and subtracting rational expressions", "medium"],
      ["4.4", "Complex fractions", "medium"],
      ["4.5", "Vertical and horizontal asymptotes", "medium"],
      ["4.6", "Holes and removable discontinuities", "medium"],
      ["4.7", "Slant and oblique asymptotes", "medium"],
      ["4.8", "Graphing rational functions", "medium"],
      ["4.9", "Solving rational equations and extraneous solutions", "medium"],
      ["4.10", "Rational inequalities", "medium"],
      ["4.11", "Variation and applications", "medium"],
    ],
  ],
  [
    "unit-5",
    "Radical Functions and Rational Exponents",
    [
      ["5.1", "nth roots and radical notation", "easy"],
      ["5.2", "Rational exponents", "medium"],
      ["5.3", "Simplifying radical expressions", "medium"],
      ["5.4", "Operations with radicals and rationalizing denominators", "medium"],
      ["5.5", "Graphing square root and cube root functions", "medium"],
      ["5.6", "Solving radical equations", "medium"],
      ["5.7", "Function operations", "medium"],
      ["5.8", "Function composition", "medium"],
      ["5.9", "Inverse functions and one-to-one behavior", "medium"],
      ["5.10", "Verifying inverses algebraically and graphically", "hard"],
    ],
  ],
  [
    "unit-6",
    "Exponential and Logarithmic Functions",
    [
      ["6.1", "Exponential growth and decay", "medium"],
      ["6.2", "The natural base e", "medium"],
      ["6.3", "Graphing exponential functions", "medium"],
      ["6.4", "Logarithms and logarithmic notation", "easy"],
      ["6.5", "Graphing logarithmic functions", "medium"],
      ["6.6", "Properties of logarithms", "medium"],
      ["6.7", "The change of base formula", "medium"],
      ["6.8", "Solving exponential equations", "medium"],
      ["6.9", "Solving logarithmic equations", "medium"],
      ["6.10", "Compound and continuously compounded interest", "medium"],
      ["6.11", "Exponential and logarithmic modeling", "hard"],
      ["6.12", "Introduction to logistic growth", "medium"],
    ],
  ],
  [
    "unit-7",
    "Trigonometric Functions",
    [
      ["7.1", "Angles and radian measure", "medium"],
      ["7.2", "The unit circle", "medium"],
      ["7.3", "Right triangle trigonometry review", "easy"],
      ["7.4", "Trigonometric functions of any angle", "medium"],
      ["7.5", "Reference angles", "medium"],
      ["7.6", "Graphing sine and cosine", "medium"],
      ["7.7", "Amplitude, period, phase shift, and vertical shift", "medium"],
      ["7.8", "Graphing tangent, cotangent, secant, and cosecant", "medium"],
      ["7.9", "Inverse trigonometric functions", "medium"],
      ["7.10", "Solving trigonometric equations", "medium"],
      ["7.11", "Fundamental trigonometric identities", "medium"],
      ["7.12", "Verifying identities", "hard"],
      ["7.13", "Sum and difference formulas", "medium"],
      ["7.14", "Double-angle and half-angle formulas", "medium"],
      ["7.15", "The Law of Sines and the Law of Cosines", "medium"],
      ["7.16", "Modeling periodic phenomena", "hard"],
    ],
  ],
  [
    "unit-8",
    "Sequences and Series",
    [
      ["8.1", "Sequences and recursive definitions", "easy"],
      ["8.2", "Arithmetic sequences", "medium"],
      ["8.3", "Arithmetic series", "medium"],
      ["8.4", "Geometric sequences", "medium"],
      ["8.5", "Geometric series", "medium"],
      ["8.6", "Infinite geometric series and convergence", "hard"],
      ["8.7", "Sigma notation", "easy"],
      ["8.8", "Mathematical induction", "hard"],
    ],
  ],
  [
    "unit-9",
    "Conic Sections",
    [
      ["9.1", "Distance and midpoint in the coordinate plane", "medium"],
      ["9.2", "Parabolas: focus and directrix", "medium"],
      ["9.3", "Circles", "medium"],
      ["9.4", "Ellipses", "medium"],
      ["9.5", "Hyperbolas", "medium"],
      ["9.6", "Classifying conics from the general equation", "medium"],
      ["9.7", "Systems involving conic sections", "medium"],
    ],
  ],
  [
    "unit-10",
    "Probability and Statistics",
    [
      ["10.1", "Permutations and combinations", "medium"],
      ["10.2", "Probability of compound events", "medium"],
      ["10.3", "Conditional probability and independence", "medium"],
      ["10.4", "Binomial distributions", "medium"],
      ["10.5", "Normal distributions and z-scores", "medium"],
      ["10.6", "Sampling and experimental design", "medium"],
      ["10.7", "Margin of error and simulation", "medium"],
      ["10.8", "Regression models: linear, quadratic, and exponential", "medium"],
    ],
  ],
];

export const PRECALCULUS: UnitSpec[] = [
  [
    "unit-1",
    "Functions and Their Properties",
    [
      ["1.1", "Function notation, domain, and range", "easy"],
      ["1.2", "Increasing, decreasing, and extrema", "medium"],
      ["1.3", "Symmetry: even and odd functions", "medium"],
      ["1.4", "Average rate of change", "medium"],
      ["1.5", "Concavity and changing rates of change", "medium"],
      ["1.6", "Piecewise-defined functions", "medium"],
      ["1.7", "Transformations of functions", "medium"],
      ["1.8", "Function composition", "medium"],
      ["1.9", "Inverse functions and domain restriction", "medium"],
      ["1.10", "Building and validating function models", "medium"],
    ],
  ],
  [
    "unit-2",
    "Polynomial and Rational Functions",
    [
      ["2.1", "Degree, end behavior, and zeros", "medium"],
      ["2.2", "Multiplicity and graph behavior at zeros", "medium"],
      ["2.3", "Complex zeros and the Fundamental Theorem of Algebra", "medium"],
      ["2.4", "Polynomial division, Remainder and Factor Theorems", "medium"],
      ["2.5", "Even and odd degree behavior", "medium"],
      ["2.6", "Rational function domains and holes", "medium"],
      ["2.7", "Vertical, horizontal, and slant asymptotes", "medium"],
      ["2.8", "Graphing rational functions", "medium"],
      ["2.9", "Polynomial and rational inequalities", "medium"],
      ["2.10", "Modeling with polynomial and rational functions", "hard"],
      ["2.11", "Model selection, regression, and residual analysis", "medium"],
    ],
  ],
  [
    "unit-3",
    "Exponential and Logarithmic Functions",
    [
      ["3.1", "Arithmetic and geometric sequences", "medium"],
      ["3.2", "Exponential function forms and growth patterns", "medium"],
      ["3.3", "The natural base e", "medium"],
      ["3.4", "Exponential transformations and asymptotic behavior", "medium"],
      ["3.5", "Logarithmic functions as inverses", "medium"],
      ["3.6", "Properties of logarithms", "medium"],
      ["3.7", "Solving exponential and logarithmic equations", "medium"],
      ["3.8", "Exponential and logarithmic inequalities", "medium"],
      ["3.9", "Semi-log plots and linearization of data", "medium"],
      ["3.10", "Exponential, logarithmic, and logistic modeling", "hard"],
    ],
  ],
  [
    "unit-4",
    "Trigonometric and Polar Functions",
    [
      ["4.1", "Periodic phenomena and cycles", "medium"],
      ["4.2", "Radian measure and arc length", "medium"],
      ["4.3", "The unit circle and definitions of sine and cosine", "easy"],
      ["4.4", "Graphs of sine and cosine", "medium"],
      ["4.5", "Sinusoidal transformations: amplitude, period, phase shift, midline", "medium"],
      ["4.6", "Sinusoidal function modeling", "hard"],
      ["4.7", "The tangent function and its graph", "medium"],
      ["4.8", "Reciprocal trigonometric functions", "medium"],
      ["4.9", "Inverse trigonometric functions and restricted domains", "medium"],
      ["4.10", "Solving trigonometric equations", "medium"],
      ["4.11", "Pythagorean and sum/difference identities", "medium"],
      ["4.12", "Double-angle and half-angle identities", "medium"],
      ["4.13", "Verifying and proving identities", "hard"],
      ["4.14", "The Law of Sines and the Law of Cosines", "medium"],
      ["4.15", "Polar coordinates and coordinate conversion", "medium"],
      ["4.16", "Graphs of polar functions", "medium"],
      ["4.17", "Rates of change in polar functions", "medium"],
    ],
  ],
  [
    "unit-5",
    "Vectors, Matrices, and Parametric Equations",
    [
      ["5.1", "Vectors in two dimensions", "medium"],
      ["5.2", "Vector operations and magnitude", "medium"],
      ["5.3", "Unit vectors and direction angles", "medium"],
      ["5.4", "The dot product and the angle between vectors", "medium"],
      ["5.5", "Vector applications: force, velocity, and navigation", "medium"],
      ["5.6", "Parametric equations and their graphs", "medium"],
      ["5.7", "Eliminating the parameter", "medium"],
      ["5.8", "Parametrically defined motion and modeling", "hard"],
      ["5.9", "Matrix operations and inverses", "medium"],
      ["5.10", "Matrices as transformations of the plane", "medium"],
      ["5.11", "Solving systems using matrices", "medium"],
      ["5.12", "Linear transformations and determinants", "medium"],
    ],
  ],
  [
    "unit-6",
    "Conic Sections and Analytic Geometry",
    [
      ["6.1", "Parabolas", "medium"],
      ["6.2", "Ellipses", "medium"],
      ["6.3", "Hyperbolas", "medium"],
      ["6.4", "Eccentricity and classification of conics", "medium"],
      ["6.5", "Rotation of axes", "hard"],
      ["6.6", "Conic sections in polar form", "medium"],
      ["6.7", "Conic sections in parametric form", "medium"],
    ],
  ],
  [
    "unit-7",
    "Sequences, Series, and Introduction to Limits",
    [
      ["7.1", "Explicit and recursive sequences", "medium"],
      ["7.2", "Arithmetic and geometric series", "medium"],
      ["7.3", "Sigma notation and summation formulas", "easy"],
      ["7.4", "Infinite series and convergence", "hard"],
      ["7.5", "The Binomial Theorem", "medium"],
      ["7.6", "Mathematical induction", "hard"],
      ["7.7", "The intuitive concept of a limit", "medium"],
      ["7.8", "Estimating limits from graphs and tables", "easy"],
      ["7.9", "Limit laws and algebraic evaluation", "medium"],
      ["7.10", "One-sided limits and continuity", "medium"],
      ["7.11", "Limits at infinity and end behavior", "medium"],
      ["7.12", "The difference quotient and the tangent line problem", "medium"],
    ],
  ],
];

export const AP_CALCULUS_AB: UnitSpec[] = [
  [
    "unit-1",
    "Limits and Continuity",
    [
      ["1.1", "Introducing calculus: can change occur at an instant?", "easy"],
      ["1.2", "Defining limits and using limit notation", "easy"],
      ["1.3", "Estimating limit values from graphs", "easy"],
      ["1.4", "Estimating limit values from tables", "easy"],
      ["1.5", "Determining limits using algebraic properties of limits", "medium"],
      ["1.6", "Determining limits using algebraic manipulation", "medium"],
      ["1.7", "Selecting procedures for determining limits", "hard"],
      ["1.8", "Determining limits using the Squeeze Theorem", "hard"],
      ["1.9", "Connecting multiple representations of limits", "medium"],
      ["1.10", "Exploring types of discontinuities", "medium"],
      ["1.11", "Defining continuity at a point", "easy"],
      ["1.12", "Confirming continuity over an interval", "medium"],
      ["1.13", "Removing discontinuities", "medium"],
      ["1.14", "Connecting infinite limits and vertical asymptotes", "medium"],
      ["1.15", "Connecting limits at infinity and horizontal asymptotes", "medium"],
      ["1.16", "Working with the Intermediate Value Theorem", "medium"],
    ],
  ],
  [
    "unit-2",
    "Differentiation — Definition and Fundamental Properties",
    [
      ["2.1", "Defining average and instantaneous rates of change at a point", "easy"],
      ["2.2", "Defining the derivative of a function and using derivative notation", "easy"],
      ["2.3", "Estimating derivatives of a function at a point", "medium"],
      ["2.4", "Connecting differentiability and continuity", "medium"],
      ["2.5", "Applying the Power Rule", "medium"],
      ["2.6", "Derivative rules: constant, sum, difference, and constant multiple", "medium"],
      ["2.7", "Derivatives of cos x, sin x, eˣ, and ln x", "medium"],
      ["2.8", "The Product Rule", "medium"],
      ["2.9", "The Quotient Rule", "medium"],
      ["2.10", "Derivatives of tangent, cotangent, secant, and cosecant", "medium"],
    ],
  ],
  [
    "unit-3",
    "Differentiation — Composite, Implicit, and Inverse Functions",
    [
      ["3.1", "The Chain Rule", "medium"],
      ["3.2", "Implicit differentiation", "hard"],
      ["3.3", "Differentiating inverse functions", "medium"],
      ["3.4", "Differentiating inverse trigonometric functions", "medium"],
      ["3.5", "Selecting procedures for calculating derivatives", "hard"],
      ["3.6", "Calculating higher-order derivatives", "medium"],
    ],
  ],
  [
    "unit-4",
    "Contextual Applications of Differentiation",
    [
      ["4.1", "Interpreting the meaning of the derivative in context", "medium"],
      ["4.2", "Straight-line motion: connecting position, velocity, and acceleration", "medium"],
      ["4.3", "Rates of change in applied contexts other than motion", "medium"],
      ["4.4", "Introduction to related rates", "medium"],
      ["4.5", "Solving related rates problems", "hard"],
      ["4.6", "Approximating values of a function using local linearity and linearization", "medium"],
      ["4.7", "Using L'Hospital's Rule for determining limits of indeterminate forms", "hard"],
    ],
  ],
  [
    "unit-5",
    "Analytical Applications of Differentiation",
    [
      ["5.1", "Using the Mean Value Theorem", "medium"],
      ["5.2", "Extreme Value Theorem, global versus local extrema, and critical points", "medium"],
      ["5.3", "Determining intervals on which a function is increasing or decreasing", "medium"],
      ["5.4", "Using the First Derivative Test to determine relative extrema", "medium"],
      ["5.5", "Using the Candidates Test to determine absolute extrema", "medium"],
      ["5.6", "Determining concavity of functions over their domains", "medium"],
      ["5.7", "Using the Second Derivative Test to determine extrema", "medium"],
      ["5.8", "Sketching graphs of functions and their derivatives", "medium"],
      ["5.9", "Connecting a function, its first derivative, and its second derivative", "medium"],
      ["5.10", "Introduction to optimization problems", "hard"],
      ["5.11", "Solving optimization problems", "hard"],
      ["5.12", "Exploring behaviors of implicit relations", "hard"],
    ],
  ],
  [
    "unit-6",
    "Integration and Accumulation of Change",
    [
      ["6.1", "Exploring accumulations of change", "medium"],
      ["6.2", "Approximating areas with Riemann sums", "medium"],
      ["6.3", "Riemann sums, summation notation, and definite integral notation", "easy"],
      ["6.4", "The Fundamental Theorem of Calculus and accumulation functions", "medium"],
      ["6.5", "Interpreting the behavior of accumulation functions involving area", "medium"],
      ["6.6", "Applying properties of definite integrals", "medium"],
      ["6.7", "The Fundamental Theorem of Calculus and definite integrals", "medium"],
      ["6.8", "Finding antiderivatives and indefinite integrals: basic rules and notation", "easy"],
      ["6.9", "Integrating using substitution", "hard"],
      ["6.10", "Integrating functions using long division and completing the square", "hard"],
      ["6.14", "Selecting techniques for antidifferentiation", "hard"],
    ],
  ],
  [
    "unit-7",
    "Differential Equations",
    [
      ["7.1", "Modeling situations with differential equations", "hard"],
      ["7.2", "Verifying solutions for differential equations", "hard"],
      ["7.3", "Sketching slope fields", "medium"],
      ["7.4", "Reasoning using slope fields", "medium"],
      ["7.6", "Finding general solutions using separation of variables", "medium"],
      ["7.7", "Finding particular solutions using initial conditions and separation of variables", "medium"],
      ["7.8", "Exponential models with differential equations", "medium"],
    ],
  ],
  [
    "unit-8",
    "Applications of Integration",
    [
      ["8.1", "Finding the average value of a function on an interval", "medium"],
      ["8.2", "Connecting position, velocity, and acceleration using integrals", "medium"],
      ["8.3", "Using accumulation functions and definite integrals in applied contexts", "medium"],
      ["8.4", "Finding the area between curves expressed as functions of x", "medium"],
      ["8.5", "Finding the area between curves expressed as functions of y", "medium"],
      ["8.6", "Finding the area between curves that intersect at more than two points", "medium"],
      ["8.7", "Volumes with cross sections: squares and rectangles", "hard"],
      ["8.8", "Volumes with cross sections: triangles and semicircles", "hard"],
      ["8.9", "Volume with the disc method: revolving around the x- or y-axis", "hard"],
      ["8.10", "Volume with the disc method: revolving around other axes", "hard"],
      ["8.11", "Volume with the washer method: revolving around the x- or y-axis", "hard"],
      ["8.12", "Volume with the washer method: revolving around other axes", "hard"],
    ],
  ],
];

/**
 * BC covers every AB topic unchanged and adds to it, so Units 1–5 are shared
 * outright rather than copied, and the BC-only topics in Units 6–8 sit back in
 * their CED numbering alongside the AB ones.
 */
export const AP_CALCULUS_BC: UnitSpec[] = [
  ...AP_CALCULUS_AB.slice(0, 5),
  [
    "unit-6",
    "Integration and Accumulation of Change",
    [
      ["6.1", "Exploring accumulations of change", "medium"],
      ["6.2", "Approximating areas with Riemann sums", "medium"],
      ["6.3", "Riemann sums, summation notation, and definite integral notation", "easy"],
      ["6.4", "The Fundamental Theorem of Calculus and accumulation functions", "medium"],
      ["6.5", "Interpreting the behavior of accumulation functions involving area", "medium"],
      ["6.6", "Applying properties of definite integrals", "medium"],
      ["6.7", "The Fundamental Theorem of Calculus and definite integrals", "medium"],
      ["6.8", "Finding antiderivatives and indefinite integrals: basic rules and notation", "easy"],
      ["6.9", "Integrating using substitution", "hard"],
      ["6.10", "Integrating functions using long division and completing the square", "hard"],
      ["6.11", "Integrating using integration by parts", "hard"],
      ["6.12", "Integrating using linear partial fractions", "hard"],
      ["6.13", "Evaluating improper integrals", "hard"],
      ["6.14", "Selecting techniques for antidifferentiation", "hard"],
    ],
  ],
  [
    "unit-7",
    "Differential Equations",
    [
      ["7.1", "Modeling situations with differential equations", "hard"],
      ["7.2", "Verifying solutions for differential equations", "hard"],
      ["7.3", "Sketching slope fields", "medium"],
      ["7.4", "Reasoning using slope fields", "medium"],
      ["7.5", "Approximating solutions using Euler's method", "medium"],
      ["7.6", "Finding general solutions using separation of variables", "medium"],
      ["7.7", "Finding particular solutions using initial conditions and separation of variables", "medium"],
      ["7.8", "Exponential models with differential equations", "medium"],
      ["7.9", "Logistic models with differential equations", "medium"],
    ],
  ],
  [
    "unit-8",
    "Applications of Integration",
    [
      ["8.1", "Finding the average value of a function on an interval", "medium"],
      ["8.2", "Connecting position, velocity, and acceleration using integrals", "medium"],
      ["8.3", "Using accumulation functions and definite integrals in applied contexts", "medium"],
      ["8.4", "Finding the area between curves expressed as functions of x", "medium"],
      ["8.5", "Finding the area between curves expressed as functions of y", "medium"],
      ["8.6", "Finding the area between curves that intersect at more than two points", "medium"],
      ["8.7", "Volumes with cross sections: squares and rectangles", "hard"],
      ["8.8", "Volumes with cross sections: triangles and semicircles", "hard"],
      ["8.9", "Volume with the disc method: revolving around the x- or y-axis", "hard"],
      ["8.10", "Volume with the disc method: revolving around other axes", "hard"],
      ["8.11", "Volume with the washer method: revolving around the x- or y-axis", "hard"],
      ["8.12", "Volume with the washer method: revolving around other axes", "hard"],
      ["8.13", "The arc length of a smooth, planar curve and distance traveled", "hard"],
    ],
  ],
  [
    "unit-9",
    "Parametric Equations, Polar Coordinates, and Vector-Valued Functions",
    [
      ["9.1", "Defining and differentiating parametric equations", "medium"],
      ["9.2", "Second derivatives of parametric equations", "medium"],
      ["9.3", "Finding arc lengths of curves given by parametric equations", "hard"],
      ["9.4", "Defining and differentiating vector-valued functions", "medium"],
      ["9.5", "Integrating vector-valued functions", "medium"],
      ["9.6", "Solving motion problems using parametric and vector-valued functions", "medium"],
      ["9.7", "Defining polar coordinates and differentiating in polar form", "medium"],
      ["9.8", "Finding the area of a polar region or the area bounded by a single polar curve", "medium"],
      ["9.9", "Finding the area of the region bounded by two polar curves", "medium"],
    ],
  ],
  [
    "unit-10",
    "Infinite Sequences and Series",
    [
      ["10.1", "Defining convergent and divergent infinite series", "medium"],
      ["10.2", "Working with geometric series", "medium"],
      ["10.3", "The nth Term Test for divergence", "medium"],
      ["10.4", "Integral Test for convergence", "hard"],
      ["10.5", "Harmonic series and p-series", "medium"],
      ["10.6", "Comparison tests for convergence", "hard"],
      ["10.7", "Alternating Series Test for convergence", "hard"],
      ["10.8", "Ratio Test for convergence", "hard"],
      ["10.9", "Determining absolute or conditional convergence", "hard"],
      ["10.10", "Alternating series error bound", "hard"],
      ["10.11", "Finding Taylor polynomial approximations of functions", "hard"],
      ["10.12", "Lagrange error bound", "hard"],
      ["10.13", "Radius and interval of convergence of power series", "hard"],
      ["10.14", "Finding Taylor or Maclaurin series for a function", "hard"],
      ["10.15", "Representing functions as power series", "hard"],
    ],
  ],
];
